Repository secureCodeBox/secureCodeBox, pull requests merged in 2020-01, with the labels that each got.

#101 Stabilize SSH Integration Tests
  .travis.yml
  demo/ssh-service/Dockerfile
  docker-compose.demo.yml
  test/ssh.test.js
Labels: testing

#87 Add WpScan to default secureCodeBox Stack
  .travis.yml
  demo/old-wordpress/Dockerfile
  demo/old-wordpress/wp.db
  demo/readme.md
  docker-compose.demo.yml
  docker-compose.yml
  docs/user-guide/usage-examples/wordpress-example.md
  test/package-lock.json
  test/wpscan.test.js
Labels: security scanner, testing

#103 Ncrack scanner
  .travis.yml
  docker-compose.yml
  test/ncrack.test.js
Labels: security scanner

#100 Docs 📚: Multi Tenancy
  docs/user-guide/README.md
  docs/user-guide/multi-tenancy/README.md
  docs/user-guide/multi-tenancy/scb_multi_tenancy.drawio
  docs/user-guide/multi-tenancy/scb_multi_tenancy.png
  test/ssh.test.js
  test/wpscan.test.js
Labels: documentation
