Repository secureCodeBox/secureCodeBox, pull requests merged in 2020-12, with the labels that each got.

#237 Increase Lease Duration and Renew Deadline
  operator/main.go
Labels: bug

#240 Gitleaks custom config and direct commit URL
  .gitignore
  scanners/gitleaks/README.md
  scanners/gitleaks/README.md.gotmpl
  scanners/gitleaks/examples/provide-own-rules/README.md
  scanners/gitleaks/examples/provide-own-rules/scan.yaml
  scanners/gitleaks/parser/Dockerfile
  scanners/gitleaks/parser/__testFiles__/test-report-small.json
  scanners/gitleaks/parser/package-lock.json
  scanners/gitleaks/parser/package.json
  scanners/gitleaks/parser/parser.js
  scanners/gitleaks/parser/parser.test.js
  scanners/screenshooter/parser/Dockerfile
  scanners/screenshooter/parser/package-lock.json
Labels: enhancement, security scanner

#236 Encrypt Ncrack passwords (closes #209)
  scanners/ncrack/README.md
  scanners/ncrack/README.md.gotmpl
  scanners/ncrack/parser/__testFiles__/public_key.pem
  scanners/ncrack/parser/parser.js
  scanners/ncrack/parser/parser.test.js
  scanners/ncrack/templates/ncrack-parse-definition.yaml
  scanners/ncrack/values.yaml
Labels: security scanner

#225 ADR to Propose Hashing Scanner Findings to Detect Duplicates
  docs/adr/adr_0007.adoc
Labels: documentation, enhancement

#246 Add Kubernetes 1.20 to supported versions
  .github/workflows/ci.yaml
Labels: ci, testing

#242 Added ImagePullPolicy to parseDefintion and scanCompletionHook
  operator/apis/execution/v1/parsedefinition_types.go
  operator/apis/execution/v1/scan_types.go
  operator/apis/execution/v1/scancompletionhook.go
  operator/apis/execution/v1/scheduledscan_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_parsedefinitions.yaml
  operator/config/crd/bases/execution.securecodebox.io_scancompletionhooks.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_parsedefinitions.yaml
  operator/crds/execution.securecodebox.io_scancompletionhooks.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: CRD, enhancement

#247 Support AWS IAM Roles to Service Account Mapping (IRSA) for S3 Authentication
  operator/README.md
  operator/README.md.gotmpl
  operator/controllers/execution/scans/scan_controller.go
  operator/go.mod
  operator/go.sum
  operator/templates/manager/manager.yaml
  operator/values.yaml
Labels: enhancement

#243 Updated Amass scanner to latest release version v3.10.5
  scanners/amass/Chart.yaml
  scanners/amass/parser/__snapshots__/parser.test.js.snap
  scanners/amass/parser/__testFiles__/empty.jsonl
  scanners/amass/parser/__testFiles__/example.com.jsonl
  scanners/amass/parser/parser.test.js
Labels: dependencies

#244 Added backoffLimit configuration option to all scan Jobs
  operator/controllers/execution/scans/job.go
  scanners/amass/README.md
  scanners/amass/templates/amass-scan-type.yaml
  scanners/amass/values.yaml
  scanners/git-repo-scanner/README.md
  scanners/git-repo-scanner/templates/git-repo-scanner-scan-type.yaml
  scanners/git-repo-scanner/values.yaml
  scanners/gitleaks/README.md
  scanners/gitleaks/templates/gitleaks-scan-type.yaml
  scanners/gitleaks/values.yaml
  scanners/kube-hunter/README.md
  scanners/kube-hunter/templates/kubehunter-scan-type.yaml
  scanners/kube-hunter/values.yaml
  scanners/kubeaudit/README.md
  scanners/kubeaudit/templates/kubeaudit-scan-type.yaml
  scanners/kubeaudit/values.yaml
  scanners/ncrack/README.md
  scanners/ncrack/templates/ncrack-scan-type.yaml
  scanners/ncrack/values.yaml
  scanners/nikto/README.md
  scanners/nikto/templates/nikto-scan-type.yaml
  scanners/nikto/values.yaml
  scanners/nmap/README.md
  scanners/nmap/templates/nmap-scan-type.yaml
  scanners/nmap/values.yaml
  scanners/screenshooter/templates/screenshooter-scan-type.yaml
  scanners/screenshooter/values.yaml
  scanners/ssh_scan/README.md
  scanners/ssh_scan/templates/ssh-scan-scan-type.yaml
  scanners/ssh_scan/values.yaml
  scanners/sslyze/README.md
  scanners/sslyze/templates/sslyze-scan-type.yaml
  scanners/sslyze/values.yaml
  scanners/test-scan/README.md
  scanners/test-scan/templates/test-scan-scan-type.yaml
  scanners/test-scan/values.yaml
  scanners/trivy/README.md
  scanners/trivy/templates/trivy-scan-type.yaml
  scanners/trivy/values.yaml
  scanners/wpscan/README.md
  scanners/wpscan/templates/wpscan-scan-type.yaml
  scanners/wpscan/values.yaml
  scanners/zap/README.md
  scanners/zap/templates/zap-scan-type.yaml
  scanners/zap/values.yaml
Labels: CRD, enhancement

#249 Update diagrams
  docs/resources/scb-architecture.drawio
  docs/resources/scb-architecture.svg
Labels: documentation

#251 Update ZAP and Integrations Tests for ZAP 2.10.0
  scanners/zap/Chart.yaml
  scanners/zap/README.md
  scanners/zap/values.yaml
  tests/integration/scanner/zap.test.js
Labels: dependencies

#266 🐞 Bugfixed the image tag reference in the kube-hunter helmchart template
  scanners/kube-hunter/templates/kubehunter-scan-type.yaml
Labels: bug

#260 Bugfixing some hook HelmChart issues
  hooks/declarative-subsequent-scans/README.md
  hooks/declarative-subsequent-scans/values.yaml
  hooks/finding-post-processing/README.md
  hooks/finding-post-processing/README.md.gotmpl
  hooks/finding-post-processing/helm2.Chart.yaml
  hooks/finding-post-processing/values.yaml
  hooks/generic-webhook/README.md
  hooks/generic-webhook/values.yaml
  hooks/persistence-elastic/README.md
  hooks/persistence-elastic/values.yaml
  hooks/update-field/README.md
  hooks/update-field/values.yaml
Labels: documentation

#259 Updating some npm sdk dependencies.
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
  parser-sdk/nodejs/parser-wrapper.js
  tests/integration/package-lock.json
  tests/integration/package.json
Labels: dependencies
