Repository secureCodeBox/secureCodeBox, pull requests merged in 2020-10, with the labels that each got.

#144 Update References to Github Repository
  .github/ISSUE_TEMPLATE/new_hook.md
  .github/ISSUE_TEMPLATE/new_security_scanner.md
  README.md
  docs/glossary.md
  docs/versioning.md
  hooks/declarative-subsequent-scans/package.json
  hooks/declarative-subsequent-scans/templates/NOTES.txt
  hooks/generic-webhook/package.json
  hooks/package.json
  hooks/persistence-elastic/package.json
  hooks/update-field/package.json
  lurcher/go.mod
  operator/Chart.yaml
  operator/PROJECT
  operator/apis/cascading/v1/cascadingrule_types.go
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/job.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_controller.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/controllers/execution/scheduledscan_controller.go
  operator/controllers/execution/suite_test.go
  operator/go.mod
  operator/go.sum
  operator/helm2.Chart.yaml
  operator/internal/telemetry/telemetry.go
  operator/main.go
  package.json
  scanners/amass/Chart.yaml
  scanners/amass/helm2.Chart.yaml
  scanners/kube-hunter/Chart.yaml
  scanners/kube-hunter/helm2.Chart.yaml
  scanners/ncrack/Chart.yaml
  scanners/ncrack/helm2.Chart.yaml
  scanners/nikto/Chart.yaml
  scanners/nikto/helm2.Chart.yaml
  scanners/nmap/Chart.yaml
  scanners/nmap/helm2.Chart.yaml
  scanners/package.json
  scanners/ssh_scan/Chart.yaml
  scanners/ssh_scan/helm2.Chart.yaml
  scanners/sslyze/Chart.yaml
  scanners/sslyze/helm2.Chart.yaml
  scanners/trivy/Chart.yaml
  scanners/trivy/helm2.Chart.yaml
  scanners/wpscan/Chart.yaml
  scanners/wpscan/helm2.Chart.yaml
  scanners/zap/Chart.yaml
  scanners/zap/helm2.Chart.yaml
Labels: maintenance

#145 Resolve open todo in cascading scans post install notes
  hooks/declarative-subsequent-scans/templates/NOTES.txt
Labels: documentation

#147 Updated readme badges
  .github/workflows/ci.yaml
  README.md
Labels: documentation

#151 feature/gitleaks-scanner (closes #135)
  .github/workflows/ci.yaml
  scanners/gitleaks/.helmignore
  scanners/gitleaks/Chart.yaml
  scanners/gitleaks/README.md
  scanners/gitleaks/README.md.gotmpl
  scanners/gitleaks/examples/multi-juicer/README.md
  scanners/gitleaks/examples/multi-juicer/scan.yaml
  scanners/gitleaks/examples/private-repository/README.md
  scanners/gitleaks/examples/private-repository/scan.yaml
  scanners/gitleaks/helm2.Chart.yaml
  scanners/gitleaks/parser/Dockerfile
  scanners/gitleaks/parser/__testFiles__/test-empty-report.json
  scanners/gitleaks/parser/__testFiles__/test-report.json
  scanners/gitleaks/parser/parser.js
  scanners/gitleaks/parser/parser.test.js
  scanners/gitleaks/scanner/Dockerfile
  scanners/gitleaks/scanner/wrapper.sh
  scanners/gitleaks/templates/gitleaks-parse-definition.yaml
  scanners/gitleaks/templates/gitleaks-scan-type.yaml
  scanners/gitleaks/values.yaml
Labels: security scanner

#155 Bugfixing helmchart kubeVersion
  hooks/declarative-subsequent-scans/Chart.yaml
  hooks/declarative-subsequent-scans/helm2.Chart.yaml
  hooks/generic-webhook/Chart.yaml
  hooks/generic-webhook/helm2.Chart.yaml
  hooks/persistence-elastic/Chart.yaml
  hooks/persistence-elastic/helm2.Chart.yaml
  hooks/update-field/Chart.yaml
  hooks/update-field/helm2.Chart.yaml
  operator/Chart.yaml
  operator/helm2.Chart.yaml
  scanners/amass/Chart.yaml
  scanners/amass/helm2.Chart.yaml
  scanners/gitleaks/Chart.yaml
  scanners/gitleaks/helm2.Chart.yaml
  scanners/kube-hunter/Chart.yaml
  scanners/kube-hunter/helm2.Chart.yaml
  scanners/ncrack/Chart.yaml
  scanners/ncrack/helm2.Chart.yaml
  scanners/nikto/Chart.yaml
  scanners/nikto/helm2.Chart.yaml
  scanners/nmap/Chart.yaml
  scanners/nmap/helm2.Chart.yaml
  scanners/ssh_scan/Chart.yaml
  scanners/ssh_scan/helm2.Chart.yaml
  scanners/sslyze/Chart.yaml
  scanners/sslyze/helm2.Chart.yaml
  scanners/trivy/Chart.yaml
  scanners/trivy/helm2.Chart.yaml
  scanners/wpscan/Chart.yaml
  scanners/wpscan/helm2.Chart.yaml
  scanners/zap/Chart.yaml
  scanners/zap/helm2.Chart.yaml
Labels: bug

#154 Bugfixing gitleaks scanner
  operator/internal/telemetry/telemetry.go
  scanners/gitleaks/README.md
  scanners/gitleaks/examples/private-repository/scan.yaml
  scanners/gitleaks/values.yaml
Labels: bug

#152 Delete Temporary Docs in README and Refer to Official Site
  README.md
Labels: documentation

#158 Update outdated link to the old website
  demo-apps/dummy-ssh/Chart.yaml
  demo-apps/dummy-ssh/README.md
  demo-apps/dummy-ssh/helm2.Chart.yaml
  operator/internal/telemetry/telemetry.go
  operator/templates/NOTES.txt
Labels: bug, documentation

#161 Decrease Minio's Default Resource Limit to 256Mi
  operator/README.md
  operator/values.yaml
Labels: bug

#142 Remove path from frontmatter and example README
  hooks/declarative-subsequent-scans/README.md
  hooks/declarative-subsequent-scans/README.md.gotmpl
  hooks/generic-webhook/README.md
  hooks/generic-webhook/README.md.gotmpl
  hooks/persistence-defectdojo/README.md
  hooks/persistence-elastic/README.md
  hooks/persistence-elastic/README.md.gotmpl
  hooks/persistence-static-report/README.md
  hooks/slack-webhook/README.md
  hooks/teams-webhook/README.md
  hooks/update-field/README.md
  hooks/update-field/README.md.gotmpl
  scanners/amass/README.md
  scanners/amass/README.md.gotmpl
  scanners/amass/examples/example.com/README.md
  scanners/gitleaks/README.md
  scanners/gitleaks/README.md.gotmpl
  scanners/kube-hunter/README.md
  scanners/kube-hunter/README.md.gotmpl
  scanners/kubeaudit/README.md
  scanners/ncrack/README.md
  scanners/ncrack/README.md.gotmpl
  scanners/nikto/README.md
  scanners/nikto/README.md.gotmpl
  scanners/nmap/README.md
  scanners/nmap/README.md.gotmpl
  scanners/ssh_scan/README.md
  scanners/ssh_scan/README.md.gotmpl
  scanners/sslyze/README.md
  scanners/sslyze/README.md.gotmpl
  scanners/trivy/README.md
  scanners/trivy/README.md.gotmpl
  scanners/zap/README.md
  scanners/zap/README.md.gotmpl
Labels: documentation

#162 Implemented new Kubeaudit Scanner
  .github/workflows/ci.yaml
  operator/controllers/execution/scans/scan_reconciler.go
  scanners/gitleaks/README.md
  scanners/gitleaks/README.md.gotmpl
  scanners/kubeaudit/.helmignore
  scanners/kubeaudit/Chart.yaml
  scanners/kubeaudit/README.md
  scanners/kubeaudit/README.md.gotmpl
  scanners/kubeaudit/examples/juice-shop/scan.yaml
  scanners/kubeaudit/parser/Dockerfile
  scanners/kubeaudit/parser/__snapshots__/parser.test.js.snap
  scanners/kubeaudit/parser/__testFiles__/juice-shop.jsonl
  scanners/kubeaudit/parser/parser.js
  scanners/kubeaudit/parser/parser.test.js
  scanners/kubeaudit/scanner/Dockerfile
  scanners/kubeaudit/scanner/wrapper.sh
  scanners/kubeaudit/templates/kubeaudit-parse-definition.yaml
  scanners/kubeaudit/templates/kubeaudit-rbac.yaml
  scanners/kubeaudit/templates/kubeaudit-scan-type.yaml
  scanners/kubeaudit/values.yaml
  tests/integration/helpers.js
  tests/integration/scanner/kubeaudit.test.js
Labels: enhancement

#164 Fix ADR Number in Title of ADR-0006
  docs/adr/adr_0006.adoc
Labels: bug, documentation

#169 Remove coming update notice from readme
  README.md
Labels: documentation

#168 Allow to configure ZAP via envFrom property
  scanners/zap/README.md
  scanners/zap/templates/zap-scan-type.yaml
  scanners/zap/values.yaml
Labels: enhancement

#173 Improving the ncrack cascadingRules
  scanners/ncrack/cascading-rules/crack-ftp.yaml
  scanners/ncrack/cascading-rules/crack-mssql.yaml
  scanners/ncrack/cascading-rules/crack-mysql.yaml
  scanners/ncrack/cascading-rules/crack-postgresql.yaml
  scanners/ncrack/cascading-rules/crack-rdp.yaml
  scanners/ncrack/cascading-rules/crack-smb.yaml
  scanners/ncrack/cascading-rules/crack-ssh.yaml
  scanners/ncrack/cascading-rules/crack-telnet.yaml
  scanners/ncrack/cascading-rules/crack-vnc.yaml
Labels: enhancement, security scanner

#174 Fix Typo in Nikto Image Name
  scanners/nikto/README.md
  scanners/nikto/values.yaml
Labels: bug

#178 Improving demo-apps helmCharts
  demo-apps/bodgeit/README.md
  demo-apps/bodgeit/README.md.gotmpl
  demo-apps/bodgeit/templates/deployment.yaml
  demo-apps/bodgeit/values.yaml
  demo-apps/dummy-ssh/README.md
  demo-apps/dummy-ssh/README.md.gotmpl
  demo-apps/dummy-ssh/templates/deployment.yaml
  demo-apps/dummy-ssh/values.yaml
  demo-apps/http-webhook/README.md
  demo-apps/http-webhook/README.md.gotmpl
  demo-apps/http-webhook/values.yaml
  demo-apps/juice-shop/README.md
  demo-apps/juice-shop/README.md.gotmpl
  demo-apps/juice-shop/templates/deployment.yaml
  demo-apps/juice-shop/values.yaml
  demo-apps/old-wordpress/README.md
  demo-apps/old-wordpress/README.md.gotmpl
  demo-apps/old-wordpress/templates/deployment.yaml
  demo-apps/old-wordpress/values.yaml
  demo-apps/swagger-petstore/README.md
  demo-apps/swagger-petstore/README.md.gotmpl
  demo-apps/swagger-petstore/templates/deployment.yaml
  demo-apps/swagger-petstore/values.yaml
Labels: enhancement

#176 Switch ZAP Output Format to XML
  scanners/zap/parser/.dockerignore
  scanners/zap/parser/Dockerfile
  scanners/zap/parser/__snapshots__/parser.test.js.snap
  scanners/zap/parser/__testFiles__/docs.securecodebox.io.xml
  scanners/zap/parser/__testFiles__/example.com.json
  scanners/zap/parser/__testFiles__/example.com.xml
  scanners/zap/parser/__testFiles__/juice-shop.json
  scanners/zap/parser/__testFiles__/juice-shop.xml
  scanners/zap/parser/__testFiles__/nginx.xml
  scanners/zap/parser/__testFiles__/not-found.xml
  scanners/zap/parser/package-lock.json
  scanners/zap/parser/package.json
  scanners/zap/parser/parser.js
  scanners/zap/parser/parser.test.js
  scanners/zap/templates/zap-parse-definition.yaml
  scanners/zap/templates/zap-scan-type.yaml
Labels: enhancement, persistence store

#165 Improved (Un-)Install scripts
  bin/install-all.sh
  bin/install.sh
  bin/uninstall-all.sh
  bin/uninstall.sh
Labels: enhancement

#177 Vagrant all in one
  Vagrantfile
  bin/install-minikube.sh
Labels: enhancement

#185 Add notes on the wpscan examples
  scanners/wpscan/examples/example.com/README.md
  scanners/wpscan/examples/old-wordpress/README.md
Labels: documentation
