Repository secureCodeBox/secureCodeBox, pull requests merged in 2020-11, with the labels that each got.

#183 Adds git-repo-scanner
  .github/workflows/ci.yaml
  hooks/declarative-subsequent-scans/Dockerfile
  hooks/declarative-subsequent-scans/hook.test.js
  hooks/declarative-subsequent-scans/hook.ts
  hooks/declarative-subsequent-scans/scan-helpers.ts
  scanners/git-repo-scanner/.helmignore
  scanners/git-repo-scanner/Chart.yaml
  scanners/git-repo-scanner/README.md
  scanners/git-repo-scanner/README.md.gotmpl
  scanners/git-repo-scanner/examples/github-secureCodeBox-scan/README.md
  scanners/git-repo-scanner/examples/github-secureCodeBox-scan/scan.yaml
  scanners/git-repo-scanner/examples/gitlab-group-scan/README.md
  scanners/git-repo-scanner/examples/gitlab-group-scan/scan.yaml
  scanners/git-repo-scanner/helm2.Chart.yaml
  scanners/git-repo-scanner/parser/Dockerfile
  scanners/git-repo-scanner/parser/__testFiles__/git-scanner-test-findings.json
  scanners/git-repo-scanner/parser/parser.js
  scanners/git-repo-scanner/parser/parser.test.js
  scanners/git-repo-scanner/scanner/Dockerfile
  scanners/git-repo-scanner/scanner/git_repo_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner_test.py
  scanners/git-repo-scanner/scanner/requirements.txt
  scanners/git-repo-scanner/templates/git-repo-scanner-parse-definition.yaml
  scanners/git-repo-scanner/templates/git-repo-scanner-scan-type.yaml
  scanners/git-repo-scanner/values.yaml
  scanners/gitleaks/README.md
  scanners/gitleaks/README.md.gotmpl
  scanners/gitleaks/cascading-rules/gitleaks-scan-github-private.yaml
  scanners/gitleaks/cascading-rules/gitleaks-scan-github-public.yaml
  scanners/gitleaks/cascading-rules/gitleaks-scan-gitlab-private.yaml
  scanners/gitleaks/cascading-rules/gitleaks-scan-gitlab-public.yaml
  scanners/gitleaks/templates/cascading-rules.yaml
Labels: security scanner

#182 Adding unattended mode to install script
  bin/install.sh
Labels: enhancement

#195 Fix Helm2 Chart Containing the Packaged Helm3 Chart
  .github/workflows/helm-charts.yaml
  operator/.helmignore
Labels: bug

#191 Vagrant install
  Vagrantfile
  bin/install-minikube.sh
Labels: enhancement

#200 Fixing docs for demo-apps
  demo-apps/bodgeit/README.md
  demo-apps/bodgeit/README.md.gotmpl
  demo-apps/dummy-ssh/Chart.yaml
  demo-apps/dummy-ssh/README.md
  demo-apps/dummy-ssh/README.md.gotmpl
  demo-apps/dummy-ssh/helm2.Chart.yaml
  demo-apps/http-webhook/README.md
  demo-apps/http-webhook/README.md.gotmpl
  demo-apps/juice-shop/Chart.yaml
  demo-apps/juice-shop/README.md
  demo-apps/juice-shop/README.md.gotmpl
  demo-apps/juice-shop/helm2.Chart.yaml
  demo-apps/old-wordpress/Chart.yaml
  demo-apps/old-wordpress/README.md
  demo-apps/old-wordpress/README.md.gotmpl
  demo-apps/old-wordpress/helm2.Chart.yaml
  demo-apps/swagger-petstore/Chart.yaml
  demo-apps/swagger-petstore/README.md
  demo-apps/swagger-petstore/README.md.gotmpl
  demo-apps/swagger-petstore/helm2.Chart.yaml
  scanners/ncrack/examples/dummy-ssh/README.md
Labels: documentation

#208 Switch from beta setup-go action
  .github/workflows/ci.yaml
Labels: bug, ci

#206 Scanner/screenshooter
  .github/workflows/ci.yaml
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/serviceaccount.go
  operator/templates/rbac/role.yaml
  parser-sdk/nodejs/parser-wrapper.js
  scanners/screenshooter/.helmignore
  scanners/screenshooter/Chart.yaml
  scanners/screenshooter/README.md
  scanners/screenshooter/README.md.gotmpl
  scanners/screenshooter/cascading-rules/http.yaml
  scanners/screenshooter/examples/securecodebox.io/README.md
  scanners/screenshooter/examples/securecodebox.io/scan.yaml
  scanners/screenshooter/helm2.Chart.yaml
  scanners/screenshooter/parser/Dockerfile
  scanners/screenshooter/parser/package-lock.json
  scanners/screenshooter/parser/package.json
  scanners/screenshooter/parser/parser.js
  scanners/screenshooter/parser/parser.test.js
  scanners/screenshooter/scanner/Dockerfile
  scanners/screenshooter/scanner/wrapper.sh
  scanners/screenshooter/templates/cascading-rules.yaml
  scanners/screenshooter/templates/screenshooter-parse-definition.yaml
  scanners/screenshooter/templates/screenshooter-scan-type.yaml
  scanners/screenshooter/values.yaml
Labels: security scanner

#211 Include port in cascaded screenshooter scans
  scanners/screenshooter/cascading-rules/http.yaml
Labels: bug

#190 Adding sslyze integration tests
  .github/workflows/ci.yaml
  demo-apps/unsafe-https/.helmignore
  demo-apps/unsafe-https/Chart.yaml
  demo-apps/unsafe-https/README.md
  demo-apps/unsafe-https/README.md.gotmpl
  demo-apps/unsafe-https/helm2.Chart.yaml
  demo-apps/unsafe-https/questions.yml
  demo-apps/unsafe-https/templates/NOTES.txt
  demo-apps/unsafe-https/templates/_helpers.tpl
  demo-apps/unsafe-https/templates/deployment.yaml
  demo-apps/unsafe-https/templates/service.yaml
  demo-apps/unsafe-https/values.yaml
  scanners/sslyze/examples/unsafe-https/scan.yaml
  tests/integration/helpers.js
  tests/integration/scanner/cascade-nmap-ncrack.test.js
  tests/integration/scanner/cascade-nmap-sslyze.test.js
  tests/integration/scanner/sslyze.test.js
Labels: security scanner, testing

#217 Nikto integration tests
  .github/workflows/ci.yaml
  tests/integration/scanner/nikto.test.js
Labels: security scanner, testing

#215 Install script improvement
  bin/install.sh
Labels: enhancement

#223 Better elastic search indexing (closes #130) [2]
  hooks/persistence-elastic/README.md
  hooks/persistence-elastic/README.md.gotmpl
  hooks/persistence-elastic/hook.js
  hooks/persistence-elastic/hook.test.js
  hooks/persistence-elastic/package-lock.json
  hooks/persistence-elastic/package.json
  hooks/persistence-elastic/templates/persistence-provider.yaml
  hooks/persistence-elastic/values.yaml
Labels: enhancement, hook

#226 Fix helm chart publish pipeline
  .github/workflows/helm-charts.yaml
Labels: bug, ci

#228 Bugfixing a missing elasticsearch hook dependency
  hooks/persistence-elastic/package-lock.json
  hooks/persistence-elastic/package.json
Labels: bug

#229 Updating some npm jest dependencies
  hooks/declarative-subsequent-scans/package-lock.json
  hooks/declarative-subsequent-scans/package.json
  hooks/generic-webhook/package-lock.json
  hooks/generic-webhook/package.json
  hooks/package-lock.json
  hooks/package.json
  hooks/persistence-elastic/package-lock.json
  hooks/persistence-elastic/package.json
  hooks/update-field/package-lock.json
  hooks/update-field/package.json
  package-lock.json
  package.json
  scanners/package-lock.json
  scanners/package.json
Labels: dependencies

#231 Support for Env and File in parser and scan
  operator/apis/execution/v1/parsedefinition_types.go
  operator/apis/execution/v1/scan_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_parsedefinitions.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_parsedefinitions.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: CRD

#232 Add history limit for failed Scans in ScheduledScans
  operator/apis/execution/v1/scheduledscan_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/controllers/execution/scheduledscan_controller.go
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: CRD, enhancement

#199 Finding Post Processing
  .github/workflows/ci.yaml
  hooks/finding-post-processing/.dockerignore
  hooks/finding-post-processing/.gitignore
  hooks/finding-post-processing/.helmignore
  hooks/finding-post-processing/Chart.yaml
  hooks/finding-post-processing/Dockerfile
  hooks/finding-post-processing/README.md
  hooks/finding-post-processing/README.md.gotmpl
  hooks/finding-post-processing/hook.js
  hooks/finding-post-processing/hook.test.js
  hooks/finding-post-processing/package-lock.json
  hooks/finding-post-processing/package.json
  hooks/finding-post-processing/templates/NOTES.txt
  hooks/finding-post-processing/templates/_helpers.tpl
  hooks/finding-post-processing/templates/finding-post-processing-hook.yaml
  hooks/finding-post-processing/values.yaml
  tests/integration/hooks/__testFiles__/finding-post-processing-values.yaml
  tests/integration/hooks/finding-post-processing.test.js
Labels: enhancement
