Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-08, with the labels that each got.

#570 Remove Old Teams Webhook
  .github/workflows/ci.yaml
  hooks/package.json
  hooks/teams-webhook/.gitignore
  hooks/teams-webhook/.helm-docs.gotmpl
  hooks/teams-webhook/.helmignore
  hooks/teams-webhook/Chart.yaml
  hooks/teams-webhook/README.md
  hooks/teams-webhook/docs/README.ArtifactHub.md
  hooks/teams-webhook/docs/README.DockerHub-Hook.md
  hooks/teams-webhook/hook/.dockerignore
  hooks/teams-webhook/hook/Dockerfile
  hooks/teams-webhook/hook/__snapshots__/hook.test.js.snap
  hooks/teams-webhook/hook/__snapshots__/hook.test.js.snap.license
  hooks/teams-webhook/hook/__snapshots__/msteams-template.test.js.snap
  hooks/teams-webhook/hook/__snapshots__/msteams-template.test.js.snap.license
  hooks/teams-webhook/hook/__testfiles__/ms-teams_messageCard.json
  hooks/teams-webhook/hook/__testfiles__/ms-teams_messageCard.json.license
  hooks/teams-webhook/hook/__testfiles__/rocketchat.json
  hooks/teams-webhook/hook/__testfiles__/rocketchat.json.license
  hooks/teams-webhook/hook/__testfiles__/slack.json
  hooks/teams-webhook/hook/__testfiles__/slack.json.license
  hooks/teams-webhook/hook/hook.js
  hooks/teams-webhook/hook/hook.test.js
  hooks/teams-webhook/hook/msteams-template.js
  hooks/teams-webhook/hook/msteams-template.test.js
  hooks/teams-webhook/hook/package-lock.json
  hooks/teams-webhook/hook/package-lock.json.license
  hooks/teams-webhook/hook/package.json
  hooks/teams-webhook/hook/package.json.license
  hooks/teams-webhook/templates/NOTES.txt
  hooks/teams-webhook/templates/_helpers.tpl
  hooks/teams-webhook/templates/teams-hook.yaml
  hooks/teams-webhook/values.yaml
Labels: breaking, ci, hook, maintenance

#571 Made Scanner and Hook Titles more uniform
  hooks/notification/.helm-docs.gotmpl
  hooks/notification/README.md
  hooks/persistence-static-report/README.md
  scanners/kube-hunter/.helm-docs.gotmpl
  scanners/kube-hunter/README.md
  scanners/kubeaudit/.helm-docs.gotmpl
  scanners/kubeaudit/README.md
Labels: maintenance

#576 Added a breaking category to the generated release notes
  .github/release-drafter.yml
Labels: documentation

#579 Updated demo-target BodgeIt Docker Image Source
  demo-targets/bodgeit/README.md
  demo-targets/bodgeit/docs/README.ArtifactHub.md
  demo-targets/bodgeit/values.yaml
Labels: maintenance

#577 Updated the Upgrading hints for the upcoming SCB V3 release
  UPGRADING.md
Labels: documentation

#572 Migrate DefectDojo Hook to SCB v3 Findings Format
  hooks/persistence-defectdojo/hook/.sdkmanrc
  hooks/persistence-defectdojo/hook/build.gradle
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapper.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapper.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/models/DefectDojoImportFinding.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/models/SecureCodeBoxFinding.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapperTest.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapperTest.java
  hooks/persistence-defectdojo/hook/src/test/resources/kubehunter-scb-findings.json
Labels: persistence, defectdojo, breaking

#580 Added a sponsors section in the main readme
  README.md
  demo-targets/bodgeit/docs/README.DockerHub-Target.md
  demo-targets/dummy-ssh/docs/README.DockerHub-Target.md
  demo-targets/http-webhook/docs/README.DockerHub-Target.md
  demo-targets/juice-shop/docs/README.DockerHub-Target.md
  demo-targets/old-wordpress/docs/README.DockerHub-Target.md
  demo-targets/swagger-petstore/docs/README.DockerHub-Target.md
  demo-targets/unsafe-https/docs/README.DockerHub-Target.md
  docs/resources/sponsors/Logo_iteratec.svg
  docs/resources/sponsors/Logo_sda-se.png
  docs/resources/sponsors/Logo_timo-pagel-it-consulting.png
  hooks/cascading-scans/docs/README.DockerHub-Hook.md
  hooks/finding-post-processing/docs/README.DockerHub-Hook.md
  hooks/generic-webhook/docs/README.DockerHub-Hook.md
  hooks/notification/docs/README.DockerHub-Hook.md
  hooks/persistence-defectdojo/docs/README.DockerHub-Hook.md
  hooks/persistence-elastic/docs/README.DockerHub-Hook.md
  hooks/update-field/docs/README.DockerHub-Hook.md
  operator/docs/README.DockerHub-Core.md
  scanners/amass/docs/README.DockerHub-Parser.md
  scanners/git-repo-scanner/docs/README.DockerHub-Parser.md
  scanners/git-repo-scanner/docs/README.DockerHub-Scanner.md
  scanners/screenshooter/docs/README.DockerHub-Parser.md
  scanners/screenshooter/docs/README.DockerHub-Scanner.md
  scanners/ssh-scan/docs/README.DockerHub-Parser.md
  scanners/sslyze/docs/README.DockerHub-Parser.md
  scanners/test-scan/docs/README.DockerHub-Parser.md
  scanners/test-scan/docs/README.DockerHub-Scanner.md
  scanners/trivy/docs/README.DockerHub-Parser.md
  scanners/wpscan/docs/README.DockerHub-Parser.md
  scanners/zap-advanced/docs/README.DockerHub-Scanner.md
  scanners/zap/docs/README.DockerHub-Parser.md
Labels: documentation

#585 Post release v3 updates
  .github/workflows/ci.yaml
  .github/workflows/helm-charts-release.yaml
  auto-discovery/kubernetes/Chart.yaml
  demo-targets/bodgeit/Chart.yaml
  demo-targets/dummy-ssh/Chart.yaml
  demo-targets/http-webhook/Chart.yaml
  demo-targets/juice-shop/Chart.yaml
  demo-targets/old-wordpress/Chart.yaml
  demo-targets/swagger-petstore/Chart.yaml
  demo-targets/unsafe-https/Chart.yaml
  hooks/cascading-scans/.helmignore
  hooks/cascading-scans/Chart.yaml
  hooks/finding-post-processing/.helmignore
  hooks/finding-post-processing/Chart.yaml
  hooks/generic-webhook/.helmignore
  hooks/generic-webhook/Chart.yaml
  hooks/notification/.helmignore
  hooks/notification/Chart.yaml
  hooks/persistence-defectdojo/.helmignore
  hooks/persistence-defectdojo/Chart.yaml
  hooks/persistence-defectdojo/README.md.gotmpl
  hooks/persistence-elastic/.helmignore
  hooks/persistence-elastic/Chart.yaml
  hooks/update-field/.helmignore
  hooks/update-field/Chart.yaml
  operator/Chart.yaml
  scanners/amass/.helmignore
  scanners/amass/Chart.yaml
  scanners/angularjs-csti-scanner/.helmignore
  scanners/angularjs-csti-scanner/Chart.yaml
  scanners/git-repo-scanner/.helmignore
  scanners/git-repo-scanner/Chart.yaml
  scanners/gitleaks/.helmignore
  scanners/gitleaks/Chart.yaml
  scanners/kube-hunter/.helmignore
  scanners/kube-hunter/Chart.yaml
  scanners/kubeaudit/.helmignore
  scanners/kubeaudit/Chart.yaml
  scanners/ncrack/.helmignore
  scanners/ncrack/Chart.yaml
  scanners/nikto/.helmignore
  scanners/nikto/Chart.yaml
  scanners/nmap/.helmignore
  scanners/nmap/Chart.yaml
  scanners/screenshooter/.helmignore
  scanners/screenshooter/Chart.yaml
  scanners/ssh-scan/.helmignore
  scanners/ssh-scan/Chart.yaml
  scanners/sslyze/.helmignore
  scanners/sslyze/Chart.yaml
  scanners/test-scan/.helmignore
  scanners/test-scan/Chart.yaml
  scanners/trivy/.helmignore
  scanners/trivy/Chart.yaml
  scanners/wpscan/.helmignore
  scanners/wpscan/Chart.yaml
  scanners/zap-advanced/.helmignore
  scanners/zap-advanced/Chart.yaml
  scanners/zap/.helmignore
  scanners/zap/Chart.yaml
Labels: maintenance

#583 Cascading Scans bugfixing
  hooks/cascading-scans/hook/hook.test.js
  hooks/cascading-scans/hook/hook.ts
Labels: bug, scanner

#590 [Bugfix] Remove Name Property From Scan Spec
  scanners/trivy/templates/trivy-scan-type.yaml
Labels: bug

#588 Fix Crash in DefectDojo PersistenceProvider when Deserializing DefectDojo Timestamps
  hooks/persistence-defectdojo/hook/build.gradle
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapper.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/service/S3Service.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapperTest.java
  hooks/persistence-defectdojo/hook/src/test/resources/kubehunter-dd-findings.json
Labels: bug, defectdojo

#594 Update NPM Dependencies
  .github/workflows/ci.yaml
  hook-sdk/nodejs/package-lock.json
  hooks/cascading-scans/hook/package-lock.json
  hooks/cascading-scans/hook/package.json
  hooks/finding-post-processing/hook/package-lock.json
  hooks/finding-post-processing/hook/package.json
  hooks/generic-webhook/hook/package-lock.json
  hooks/notification/hook/package-lock.json
  hooks/package-lock.json
  hooks/persistence-elastic/hook/package-lock.json
  hooks/update-field/hook/package-lock.json
  package-lock.json
  package.json
  parser-sdk/nodejs/package-lock.json
  scanners/package-lock.json
  tests/integration/package-lock.json
Labels: bug, dependencies

#586 Update Kubernetes Versions used in CI
  .github/workflows/ci.yaml
Labels: dependencies

#597 Revert Change in Helmignore to Include the Scripts Again
  scanners/zap-advanced/.helmignore
Labels: bug

#600 Improved Test Structure and Tests in DefectDojo Hook
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/DefectDojoPersistenceProvider.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/config/PersistenceProviderConfig.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapper.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/service/ScanService.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/service/scanresult/GenericParserScanResultService.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/service/scanresult/ScanResultService.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/service/scanresult/SpecificParserScanResultService.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapperTest.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/service/ScanServiceTest.java
  hooks/persistence-defectdojo/hook/src/test/resources/nikto-raw-result.json
Labels: hook, defectdojo

#599 Fix Incorrect Path for API Import in Petstore Example
  scanners/zap-advanced/examples/demo-petstoreapi-scan-unauthenticated/scan.yaml
Labels: bug, documentation

#587 Add Secura Company logo to Sponsors Section.
  CONTRIBUTORS.md
  README.md
  docs/resources/sponsors/Logo_secura.svg
Labels: documentation

#606 Bugfixed scanner zap-advanced when used with cascadingRules
  scanners/zap-advanced/scanner/scripts/authentication/scb-oidc-password-grand-type.js
  scanners/zap-advanced/scanner/scripts/session/scb-oidc-session-management.js
  scanners/zap-advanced/scanner/tests/mocks/cascading-scan-full-local/1_zap-advanced-scan-config.yaml
  scanners/zap-advanced/scanner/tests/test_integration_zap_local.py
  scanners/zap-advanced/scanner/zapclient/zap_automation.py
Labels: bug, scanner

#603 Finding are validated in Integration Tests
  .github/workflows/ci.yaml
  parser-sdk/nodejs/Dockerfile
  parser-sdk/nodejs/parser-wrapper.js
  scanners/test-scan/parser/parser.js
  tests/integration/generic/findings-validation.test.js
Labels: testing

#616 Bugfixed scanner parseDefinitions ttlSecondsAfterFinished HelmValue inconsistencies
  scanners/kube-hunter/templates/kube-hunter-parse-definition.yaml
  scanners/ncrack/templates/ncrack-parse-definition.yaml
  scanners/nuclei/templates/nuclei-parse-definition.yaml
  scanners/ssh-scan/templates/ssh-scan-parse-definition.yaml
  scanners/typo3scan/templates/typo3scan-parse-definition.yaml
Labels: bug, scanner
