Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-01, with the labels that each got.

#270 Update Juice Shop to v12.4.0
  demo-apps/juice-shop/Chart.yaml
  demo-apps/juice-shop/helm2.Chart.yaml
Labels: dependencies

#271 Fix Parsing Error for Amass Results with a Single Identified Domain
  scanners/amass/parser/__snapshots__/parser.test.js.snap
  scanners/amass/parser/parser.js
  scanners/amass/parser/parser.test.js
Labels: bug

#272 Pinned gitleaks docker image to defined tag version
  scanners/gitleaks/scanner/Dockerfile
Labels: bug

#281 Ensure that kubeaudit is build with the intended version
  .github/workflows/ci.yaml
  scanners/kubeaudit/scanner/Dockerfile
Labels: bug, ci

#284 Ensure that CRDs are Only Contained Once in the Helm2 Chart
  .github/workflows/helm-charts.yaml
Labels: bug
