Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-05, with the labels that each got.

#401 [Bugfix] Fixing Angularjs Csti Scanner ⛑ HelmChart
  scanners/angularjs-csti-scanner/Chart.yaml
  scanners/angularjs-csti-scanner/helm2.Chart.yaml
  scanners/angularjs-csti-scanner/templates/angularjs-csti-scanner-scan-type.yaml
Labels: bug

#397 Convert ADRs to Markdown
  docs/adr/adr_0000.adoc
  docs/adr/adr_0000.md
  docs/adr/adr_0001.adoc
  docs/adr/adr_0001.md
  docs/adr/adr_0002.md
  docs/adr/adr_0003.md
  docs/adr/adr_0004.adoc
  docs/adr/adr_0004.md
  docs/adr/adr_0005.adoc
  docs/adr/adr_0005.md
  docs/adr/adr_0006.adoc
  docs/adr/adr_0006.md
  docs/adr/adr_0007.adoc
  docs/adr/adr_0007.md
  docs/adr/adr_README.md
Labels: documentation

#402 Add a ⛑ HelmChart configuration value to disable the cascadingRules installation
  hooks/declarative-subsequent-scans/README.md
  hooks/declarative-subsequent-scans/README.md.gotmpl
  scanners/gitleaks/README.md
  scanners/gitleaks/templates/cascading-rules.yaml
  scanners/gitleaks/values.yaml
  scanners/kube-hunter/README.md
  scanners/kube-hunter/templates/cascading-rules.yaml
  scanners/kube-hunter/values.yaml
  scanners/ncrack/README.md
  scanners/ncrack/templates/cascading-rules.yaml
  scanners/ncrack/values.yaml
  scanners/nikto/README.md
  scanners/nikto/templates/cascading-rules.yaml
  scanners/nikto/values.yaml
  scanners/nmap/README.md
  scanners/nmap/templates/cascading-rules.yaml
  scanners/nmap/values.yaml
  scanners/screenshooter/templates/cascading-rules.yaml
  scanners/screenshooter/values.yaml
  scanners/ssh-scan/README.md
  scanners/ssh-scan/templates/cascading-rules.yaml
  scanners/ssh-scan/values.yaml
  scanners/sslyze/README.md
  scanners/sslyze/templates/cascading-rules.yaml
  scanners/sslyze/values.yaml
  scanners/zap/README.md
  scanners/zap/templates/cascading-rules.yaml
  scanners/zap/values.yaml
Labels: enhancement

#386 Add Email Notifier To Notification Hook
  hooks/notification-hook/NotifierFactory.ts
  hooks/notification-hook/NotifierType.ts
  hooks/notification-hook/Notifiers/EMailNotifier.test.ts
  hooks/notification-hook/Notifiers/EMailNotifier.ts
  hooks/notification-hook/README.md
  hooks/notification-hook/README.md.gotmpl
  hooks/notification-hook/hook.ts
  hooks/notification-hook/notification-templates/email.njk
  hooks/notification-hook/package-lock.json
  hooks/notification-hook/package.json
  hooks/notification-hook/values.yaml
Labels: enhancement

#404 Update npm dependencies
  hooks/package-lock.json
  package-lock.json
  scanners/package-lock.json
  tests/integration/package-lock.json
  tests/integration/package.json
Labels: dependencies

#410 Remove Invalid Fields from ScanTypes and ParseDefinitions
  operator/templates/rbac/auth_proxy_client_clusterrole.yaml
  scanners/amass/templates/amass-parse-definition.yaml
  scanners/amass/templates/amass-scan-type.yaml
  scanners/angularjs-csti-scanner/templates/angularjs-csti-scanner-parse-definition.yaml
  scanners/git-repo-scanner/templates/git-repo-scanner-parse-definition.yaml
  scanners/gitleaks/templates/gitleaks-parse-definition.yaml
  scanners/kube-hunter/templates/kube-hunter-parse-definition.yaml
  scanners/kubeaudit/templates/kubeaudit-parse-definition.yaml
  scanners/kubeaudit/templates/kubeaudit-rbac.yaml
  scanners/ncrack/templates/ncrack-parse-definition.yaml
  scanners/nikto/templates/nikto-parse-definition.yaml
  scanners/nmap/templates/nmap-parse-definition.yaml
  scanners/screenshooter/templates/screenshooter-parse-definition.yaml
  scanners/ssh-scan/templates/ssh-scan-parse-definition.yaml
  scanners/ssh-scan/templates/ssh-scan-scan-type.yaml
  scanners/sslyze/templates/sslyze-parse-definition.yaml
  scanners/test-scan/templates/test-scan-parse-definition.yaml
  scanners/trivy/templates/trivy-parse-definition.yaml
  scanners/wpscan/templates/wpscan-parse-definition.yaml
  scanners/wpscan/templates/wpscan-scan-type.yaml
  scanners/zap/templates/zap-parse-definition.yaml
Labels: bug

#421 Sign Helm docs commits
  .github/workflows/helm-docs.yaml
  demo-apps/old-wordpress/README.md
  demo-apps/old-wordpress/README.md.gotmpl
  hooks/finding-post-processing/README.md
  hooks/finding-post-processing/README.md.gotmpl
  hooks/notification-hook/README.md
  hooks/notification-hook/README.md.gotmpl
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/README.md.gotmpl
  operator/README.md
  operator/README.md.gotmpl
  scanners/angularjs-csti-scanner/README.md
  scanners/angularjs-csti-scanner/README.md.gotmpl
  scanners/git-repo-scanner/README.md
  scanners/git-repo-scanner/README.md.gotmpl
  scanners/gitleaks/README.md
  scanners/gitleaks/README.md.gotmpl
  scanners/kube-hunter/README.md
  scanners/kube-hunter/README.md.gotmpl
  scanners/kubeaudit/README.md
  scanners/kubeaudit/values.yaml
  scanners/ncrack/README.md
  scanners/ncrack/README.md.gotmpl
  scanners/nikto/README.md
  scanners/nikto/README.md.gotmpl
  scanners/nmap/README.md
  scanners/nmap/README.md.gotmpl
  scanners/screenshooter/README.md
  scanners/screenshooter/README.md.gotmpl
  scanners/trivy/README.md
  scanners/trivy/README.md.gotmpl
  scanners/wpscan/README.md
  scanners/wpscan/README.md.gotmpl
  scanners/zap/README.md
  scanners/zap/README.md.gotmpl
Labels: enhancement

#424 Fix Crash in Wpscan Parser When No Wordpress Version Got Identified
  .eslintignore
  .eslintrc
  package.json
  scanners/ncrack/parser/parser.js
  scanners/wpscan/parser/__testFiles__/no-version-detected.json
  scanners/wpscan/parser/parser.js
  scanners/wpscan/parser/parser.test.js
Labels: bug, testing

#423 Allow to Configure DefectDojo Test Titles via Scan Annotations
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/README.md.gotmpl
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/models/Scan.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/strategies/VersionedEngagementsStrategy.java
Labels: defectdojo, enhancement

#428 Updating gitleaks scanner to the latest release v7.5.0
  scanners/gitleaks/Chart.yaml
  scanners/gitleaks/helm2.Chart.yaml
Labels: dependencies, scanner

#426 Updated trivy scanner to version v0.18.1
  scanners/trivy/Chart.yaml
  scanners/trivy/helm2.Chart.yaml
Labels: dependencies, scanner

#427 Updating kubeaudit scanner to latest release v0.14.1
  scanners/kubeaudit/Chart.yaml
  scanners/kubeaudit/helm2.Chart.yaml
  scanners/kubeaudit/scanner/Dockerfile
Labels: dependencies, scanner

#431 Place Request For Signed Commits More Prominently
  CONTRIBUTING.md
Labels: documentation

#433 Add "tcp://" prefix to kubehunter node locations
  scanners/kube-hunter/parser/__snapshots__/parser.test.js.snap
  scanners/kube-hunter/parser/parser.js
Labels: bug, scanner

#434 Update Base Image To Newer Version
  scanners/git-repo-scanner/scanner/Dockerfile
Labels: dependencies, python

#435 Updating trivy scanner to v.0.18.2
  scanners/trivy/Chart.yaml
  scanners/trivy/helm2.Chart.yaml
Labels: dependencies, scanner

#436 Make deduplicateOnEngagement configurable
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/README.md.gotmpl
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/models/Scan.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/strategies/VersionedEngagementsStrategy.java
Labels: defectdojo, enhancement

#440 Rename `matchExpression` to `matchExpressions` in cascading scans
  hooks/declarative-subsequent-scans/README.md
  hooks/declarative-subsequent-scans/README.md.gotmpl
  hooks/declarative-subsequent-scans/kubernetes-label-selector.test.js
  hooks/declarative-subsequent-scans/kubernetes-label-selector.ts
  operator/Chart.yaml
Labels: bug

#430 🕸 Extend the Cascading-Scans Hook to generate custom labels or annotations for subsequent scans
  hooks/declarative-subsequent-scans/hook.test.js
  hooks/declarative-subsequent-scans/hook.ts
  hooks/declarative-subsequent-scans/scan-helpers.ts
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/models/V1ScanSpecCascades.java
  operator/apis/cascading/v1/cascadingrule_types.go
  operator/apis/cascading/v1/zz_generated.deepcopy.go
  operator/apis/execution/v1/scan_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: defectdojo, hook

#442 Bugfixing operator generated code
  operator/apis/execution/v1/zz_generated.deepcopy.go
Labels: bug

#444 Drop Helm2 Charts
  .github/workflows/helm-charts.yaml
  demo-apps/bodgeit/helm2.Chart.yaml
  demo-apps/dummy-ssh/helm2.Chart.yaml
  demo-apps/juice-shop/helm2.Chart.yaml
  demo-apps/old-wordpress/helm2.Chart.yaml
  demo-apps/swagger-petstore/helm2.Chart.yaml
  demo-apps/unsafe-https/helm2.Chart.yaml
  hooks/declarative-subsequent-scans/helm2.Chart.yaml
  hooks/finding-post-processing/helm2.Chart.yaml
  hooks/generic-webhook/helm2.Chart.yaml
  hooks/notification-hook/helm2.Chart.yaml
  hooks/persistence-elastic/helm2.Chart.yaml
  hooks/teams-webhook/helm2.Chart.yaml
  hooks/update-field/helm2.Chart.yaml
  operator/helm2.Chart.yaml
  scanners/amass/helm2.Chart.yaml
  scanners/angularjs-csti-scanner/helm2.Chart.yaml
  scanners/git-repo-scanner/helm2.Chart.yaml
  scanners/gitleaks/helm2.Chart.yaml
  scanners/kube-hunter/helm2.Chart.yaml
  scanners/kubeaudit/helm2.Chart.yaml
  scanners/ncrack/helm2.Chart.yaml
  scanners/nikto/helm2.Chart.yaml
  scanners/nmap/helm2.Chart.yaml
  scanners/screenshooter/helm2.Chart.yaml
  scanners/ssh-scan/helm2.Chart.yaml
  scanners/sslyze/helm2.Chart.yaml
  scanners/test-scan/helm2.Chart.yaml
  scanners/trivy/helm2.Chart.yaml
  scanners/wpscan/helm2.Chart.yaml
  scanners/zap-advanced/.helmignore
  scanners/zap-advanced/helm2.Chart.yaml
  scanners/zap/helm2.Chart.yaml
Labels: maintenance

#446 Remove other forgotten helm 2 files after #444
  hooks/persistence-elastic/helm2.requirements.lock
  hooks/persistence-elastic/helm2.requirements.lock.license
  hooks/persistence-elastic/helm2.requirements.yaml
  operator/helm2.requirements.lock
  operator/helm2.requirements.lock.license
  operator/helm2.requirements.yaml
Labels: maintenance, skip-changelog

#449 Fix wrong container repo for the angularjs-csti-scanner
  scanners/angularjs-csti-scanner/README.md
  scanners/angularjs-csti-scanner/values.yaml
Labels: bug

#448 Wait a short time after `helm publish` to prevent indexing problems
  .github/workflows/helm-charts.yaml
Labels: ci, maintenance

#447 Build ZAP advanced as custom scanner instead of third-party scanner
  .github/workflows/ci.yaml
Labels: bug, ci, scanner

#455 Tweet on Release
  .github/workflows/release-tweet.yaml
Labels: ci

#460 Update Docker Image For Amass
  scanners/amass/Chart.yaml
Labels: bug, maintenance, scanner, testing

#441 Adds the Developer Certificate of Origin and Contributors
  CONTRIBUTORS.md
  DCO
Labels: maintenance
