Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-10, with the labels that each got.

#687 Add defaults for cascading inherit fields and disable omitEmpty
  operator/apis/execution/v1/scan_types.go
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: bug

#652 Adding a minio startup script
  bin/minio-port-forward.sh
Labels: enhancement

#688 Multitude of Makefile and integration test issue and style fixes
  common.mk
  hooks.mk
  hooks/cascading-scans/Makefile
  hooks/finding-post-processing/Makefile
  hooks/notification/Makefile
  scanners/nikto/Makefile
  scanners/typo3scan/Makefile
  tests/integration/scanner/git-repo-scanner.test.js
Labels: ci

#692 Add `ftp-anon` and `ftp-banner` nmap scripts and support for portrule scripts
  scanners/nmap/.helm-docs.gotmpl
  scanners/nmap/README.md
  scanners/nmap/parser/__testFiles__/ftp.xml
  scanners/nmap/parser/parser.js
  scanners/nmap/parser/parser.test.js
Labels: enhancement, scanner

#694 Upgrade `AMASS` scanner to latest release v3.14
  demo-targets/old-wordpress/container/Dockerfile
  scanners/amass/Chart.yaml
  scanners/amass/README.md
Labels: scanner, dependencies

#681 Added a Joomla demo-target
  .github/workflows/ci.yaml
  demo-targets/old-joomla/.helm-docs.gotmpl
  demo-targets/old-joomla/.helmignore
  demo-targets/old-joomla/Chart.yaml
  demo-targets/old-joomla/README.md
  demo-targets/old-joomla/container/Dockerfile
  demo-targets/old-joomla/docs/README.ArtifactHub.md
  demo-targets/old-joomla/docs/README.DockerHub-Target.md
  demo-targets/old-joomla/questions.yml
  demo-targets/old-joomla/templates/NOTES.txt
  demo-targets/old-joomla/templates/_helpers.tpl
  demo-targets/old-joomla/templates/deployment.yaml
  demo-targets/old-joomla/templates/ingress.yaml
  demo-targets/old-joomla/templates/service.yaml
  demo-targets/old-joomla/templates/tests/test-connection.yaml
  demo-targets/old-joomla/values.yaml
  demo-targets/old-typo3/docs/.gitkeep
  demo-targets/old-typo3/docs/README.ArtifactHub.md
  demo-targets/old-typo3/docs/README.DockerHub-Target.md
Labels: testing

#697 fix: update npm deps ./bin/npm-audit-fix-all.sh
  hooks/cascading-scans/hook/package-lock.json
  hooks/finding-post-processing/hook/package-lock.json
  hooks/generic-webhook/hook/package-lock.json
  hooks/notification/hook/package-lock.json
  hooks/package-lock.json
  hooks/persistence-elastic/hook/package-lock.json
  hooks/update-field/hook/package-lock.json
  package-lock.json
  scanners/package-lock.json
  tests/integration/package-lock.json
Labels: maintenance

#700 fix(scanner): fix scantype for nuclei
  scanners/nuclei/templates/nuclei-scan-type.yaml
Labels: bug, scanner

#698 Helm Chart: Juice-Shop - Ingress installation failed because of 'apiVersion not set'
  CONTRIBUTORS.md
  demo-targets/juice-shop/Chart.yaml
  demo-targets/juice-shop/templates/ingress.yaml
Labels: bug

#704 :construction: [Consistency] Making all cascading-rules.yaml files consistent
  scanners/typo3scan/templates/cascading-rules.yaml
  scanners/zap-advanced/templates/cascading-rules.yaml
Labels: maintenance

#702 :construction: [Consistency] Making all Chart.yaml files consistent
  scanners/amass/Chart.yaml
  scanners/angularjs-csti-scanner/Chart.yaml
  scanners/git-repo-scanner/Chart.yaml
  scanners/gitleaks/Chart.yaml
  scanners/kube-hunter/Chart.yaml
  scanners/kubeaudit/Chart.yaml
  scanners/ncrack/Chart.yaml
  scanners/nikto/Chart.yaml
  scanners/nmap/Chart.yaml
  scanners/nuclei/Chart.yaml
  scanners/screenshooter/Chart.yaml
  scanners/sslyze/Chart.yaml
  scanners/test-scan/Chart.yaml
  scanners/typo3scan/Chart.yaml
  scanners/whatweb/Chart.yaml
  scanners/wpscan/Chart.yaml
Labels: maintenance

#690 Add presigned head url to scan object
  operator/apis/execution/v1/scan_types.go
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/controllers/execution/scans/scan_controller.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/crds/execution.securecodebox.io_scans.yaml
Labels: CRD
