Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-02, with the labels that each got.

#283 Update CI Workflow With New Build-Push-Action And more parallelization
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  hooks/declarative-subsequent-scans/Dockerfile
  hooks/finding-post-processing/Dockerfile
  hooks/generic-webhook/Dockerfile
  hooks/persistence-elastic/Dockerfile
  hooks/teams-webhook/Dockerfile
  hooks/update-field/Dockerfile
  scanners/amass/parser/Dockerfile
  scanners/git-repo-scanner/parser/Dockerfile
  scanners/gitleaks/parser/Dockerfile
  scanners/gitleaks/scanner/Dockerfile
  scanners/kube-hunter/Chart.yaml
  scanners/kube-hunter/parser/Dockerfile
  scanners/kube-hunter/scanner/Dockerfile
  scanners/kubeaudit/Chart.yaml
  scanners/kubeaudit/parser/Dockerfile
  scanners/kubeaudit/scanner/Dockerfile
  scanners/ncrack/parser/Dockerfile
  scanners/ncrack/scanner/Dockerfile
  scanners/nikto/parser/Dockerfile
  scanners/nikto/scanner/Dockerfile
  scanners/nmap/parser/Dockerfile
  scanners/nmap/scanner/Dockerfile
  scanners/screenshooter/parser/Dockerfile
  scanners/ssh_scan/parser/Dockerfile
  scanners/sslyze/parser/Dockerfile
  scanners/test-scan/parser/Dockerfile
  scanners/trivy/parser/Dockerfile
  scanners/wpscan/parser/Dockerfile
  scanners/zap/parser/Dockerfile
Labels: ci

#292 Fix CI Issues for ssh-scan and teams-webhook
  .github/workflows/ci.yaml
  hooks/declarative-subsequent-scans/README.md
  hooks/declarative-subsequent-scans/values.yaml
  hooks/teams-webhook/values.yaml
  scanners/ssh-scan/.helmignore
  scanners/ssh-scan/Chart.yaml
  scanners/ssh-scan/README.md
  scanners/ssh-scan/README.md.gotmpl
  scanners/ssh-scan/cascading-rules/ssh.yaml
  scanners/ssh-scan/examples/demo-app-ssh/findings.yaml
  scanners/ssh-scan/examples/demo-app-ssh/scan.yaml
  scanners/ssh-scan/examples/demo-app-ssh/ssh-scan-results.json
  scanners/ssh-scan/examples/example.com/scan.yaml
  scanners/ssh-scan/examples/localhost/findings.yaml
  scanners/ssh-scan/examples/localhost/scan.yaml
  scanners/ssh-scan/helm2.Chart.yaml
  scanners/ssh-scan/parser/Dockerfile
  scanners/ssh-scan/parser/__testFiles__/192.168.42.42.json
  scanners/ssh-scan/parser/__testFiles__/local-network.json
  scanners/ssh-scan/parser/__testFiles__/localhost.json
  scanners/ssh-scan/parser/__testFiles__/securecodebox.io.json
  scanners/ssh-scan/parser/parser.js
  scanners/ssh-scan/parser/parser.test.js
  scanners/ssh-scan/templates/cascading-rules.yaml
  scanners/ssh-scan/templates/ssh-scan-parse-definition.yaml
  scanners/ssh-scan/templates/ssh-scan-scan-type.yaml
  scanners/ssh-scan/values.yaml
Labels: bug, ci

#289 Copy secureCodeBox annotations from scheduledScans to scans
  operator/controllers/execution/scheduledscan_controller.go
  operator/controllers/execution/scheduledscan_controller_test.go
  operator/controllers/execution/suite_test.go
  operator/go.mod
Labels: enhancement

#294 Update to Nmap 7.91
  scanners/nmap/Chart.yaml
  scanners/nmap/scanner/Dockerfile
Labels: security scanner

#298 Replace latest with a upcomming alpha release
  demo-apps/bodgeit/Chart.yaml
  demo-apps/bodgeit/helm2.Chart.yaml
  demo-apps/dummy-ssh/Chart.yaml
  demo-apps/dummy-ssh/helm2.Chart.yaml
  demo-apps/http-webhook/Chart.yaml
  demo-apps/juice-shop/Chart.yaml
  demo-apps/juice-shop/helm2.Chart.yaml
  demo-apps/old-wordpress/Chart.yaml
  demo-apps/old-wordpress/helm2.Chart.yaml
  demo-apps/swagger-petstore/Chart.yaml
  demo-apps/swagger-petstore/helm2.Chart.yaml
  demo-apps/unsafe-https/Chart.yaml
  demo-apps/unsafe-https/helm2.Chart.yaml
  hooks/declarative-subsequent-scans/Chart.yaml
  hooks/declarative-subsequent-scans/helm2.Chart.yaml
  hooks/finding-post-processing/Chart.yaml
  hooks/finding-post-processing/helm2.Chart.yaml
  hooks/generic-webhook/Chart.yaml
  hooks/generic-webhook/helm2.Chart.yaml
  hooks/persistence-elastic/Chart.yaml
  hooks/persistence-elastic/helm2.Chart.yaml
  hooks/teams-webhook/Chart.yaml
  hooks/teams-webhook/helm2.Chart.yaml
  hooks/update-field/Chart.yaml
  hooks/update-field/helm2.Chart.yaml
  operator/Chart.yaml
  operator/helm2.Chart.yaml
  scanners/amass/Chart.yaml
  scanners/amass/helm2.Chart.yaml
  scanners/git-repo-scanner/Chart.yaml
  scanners/git-repo-scanner/helm2.Chart.yaml
  scanners/gitleaks/Chart.yaml
  scanners/gitleaks/helm2.Chart.yaml
  scanners/kube-hunter/Chart.yaml
  scanners/kube-hunter/helm2.Chart.yaml
  scanners/kubeaudit/Chart.yaml
  scanners/kubeaudit/helm2.Chart.yaml
  scanners/ncrack/Chart.yaml
  scanners/ncrack/helm2.Chart.yaml
  scanners/nikto/Chart.yaml
  scanners/nikto/helm2.Chart.yaml
  scanners/nmap/Chart.yaml
  scanners/nmap/helm2.Chart.yaml
  scanners/screenshooter/Chart.yaml
  scanners/screenshooter/helm2.Chart.yaml
  scanners/ssh-scan/Chart.yaml
  scanners/ssh-scan/helm2.Chart.yaml
  scanners/sslyze/Chart.yaml
  scanners/sslyze/helm2.Chart.yaml
  scanners/test-scan/Chart.yaml
  scanners/test-scan/helm2.Chart.yaml
  scanners/trivy/Chart.yaml
  scanners/trivy/helm2.Chart.yaml
  scanners/wpscan/Chart.yaml
  scanners/wpscan/helm2.Chart.yaml
  scanners/zap/Chart.yaml
  scanners/zap/helm2.Chart.yaml
Labels: bug, ci
