Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-03, with the labels that each got.

#305 Move to seperate Kubernetes ServiceAccount for the Operator
  .github/workflows/helm-docs.yaml
  operator/README.md
  operator/controllers/execution/scans/scan_controller.go
  operator/go.mod
  operator/go.sum
  operator/templates/manager/manager.yaml
  operator/templates/rbac/auth_proxy_role_binding.yaml
  operator/templates/rbac/leader_election_role_binding.yaml
  operator/templates/rbac/role_binding.yaml
  operator/templates/rbac/serviceaccount.yaml
  operator/values.yaml
Labels: architecture, maintenance

#306 Print out Entire S3 Response when Lurcher Fails to Upload a Result Rule
  lurcher/main.go
Labels: enhancement

#299 Enable Use Of Custom Certificates
  operator/README.md
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/job.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/templates/manager/manager.yaml
  operator/values.yaml
  scanners/amass/Chart.yaml
  scanners/gitleaks/README.md
  scanners/gitleaks/values.yaml
Labels: enhancement

#314 [Snyk] Upgrade luxon from 1.25.0 to 1.26.0
  hooks/persistence-elastic/package-lock.json
  hooks/persistence-elastic/package.json
Labels: dependencies

#248 New Scanner: AngularJS CSTI Scanner (closes #216)
  .github/workflows/ci.yaml
  scanners/angularjs-csti-scanner/.helmignore
  scanners/angularjs-csti-scanner/Chart.yaml
  scanners/angularjs-csti-scanner/README.md
  scanners/angularjs-csti-scanner/README.md.gotmpl
  scanners/angularjs-csti-scanner/examples/scan-single-url/README.md
  scanners/angularjs-csti-scanner/examples/scan-single-url/scan.yaml
  scanners/angularjs-csti-scanner/examples/scan-website-with-options/README.md
  scanners/angularjs-csti-scanner/examples/scan-website-with-options/scan.yaml
  scanners/angularjs-csti-scanner/helm2.Chart.yaml
  scanners/angularjs-csti-scanner/parser/Dockerfile
  scanners/angularjs-csti-scanner/parser/__testFiles__/acstis-test-empty-findings.txt
  scanners/angularjs-csti-scanner/parser/__testFiles__/acstis-test-findings.txt
  scanners/angularjs-csti-scanner/parser/parser.js
  scanners/angularjs-csti-scanner/parser/parser.test.js
  scanners/angularjs-csti-scanner/scanner/Dockerfile
  scanners/angularjs-csti-scanner/scanner/acstis-script.py
  scanners/angularjs-csti-scanner/scanner/wrapper.sh
  scanners/angularjs-csti-scanner/templates/angularjs-csti-scanner-parse-definition.yaml
  scanners/angularjs-csti-scanner/templates/angularjs-csti-scanner-scan-type.yaml
  scanners/angularjs-csti-scanner/values.yaml
Labels: security scanner

#333 Improving and bugfixing the github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_hook.md
  .github/ISSUE_TEMPLATE/new_security_scanner.md
  .github/pull_request_template.md
  .github/release-drafter.yml
Labels: documentation

#337 Fix File Mount Options For Hooks
  operator/controllers/execution/scans/hook_reconciler.go
Labels: bug

#344 Adding first ascii cli example as svg
  README.md
  docs/resources/ascii/scb-first-start.cast
  docs/resources/ascii/scb-first-start.svg
Labels: documentation
