Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-12, with the labels that each got.

#852 Run angularjs-csti As User In Container
  scanners/angularjs-csti-scanner/.helm-docs.gotmpl
  scanners/angularjs-csti-scanner/README.md
  scanners/angularjs-csti-scanner/examples/scan-website-with-options/scan.yaml
  scanners/angularjs-csti-scanner/scanner/Dockerfile
  scanners/angularjs-csti-scanner/scanner/wrapper.sh
  scanners/angularjs-csti-scanner/templates/angularjs-csti-scanner-scan-type.yaml
  scanners/angularjs-csti-scanner/values.yaml
Labels: scanner, maintenance

#854 Fixes typo in setting the SCB-Bot changelog env variable
  .github/workflows/scb-bot.yaml
Labels: bug

#846 Update list of scantypes for telemetry
  operator/internal/telemetry/telemetry.go
Labels: maintenance

#860 Replaces the changelog in the SCB-Bot PRs with a link to release
  .github/workflows/scb-bot.yaml
Labels: bug

#858 Fix/nuclei without template cache pvc
  scanners/nuclei/.helm-docs.gotmpl
  scanners/nuclei/README.md
  scanners/nuclei/templates/nuclei-scan-type.yaml
Labels: bug, documentation

#868 Added a new sponsor logo on behalf of signal iduna
  README.md
  docs/resources/sponsors/Logo_signal-iduna.svg
Labels: documentation

#865 Docs: fix whatweb documentation
  CONTRIBUTORS.md
  scanners/whatweb/.helm-docs.gotmpl
  scanners/whatweb/README.md
  scanners/whatweb/examples/example.com/findings.yaml
  scanners/whatweb/examples/example.com/scan.yaml
Labels: documentation

#878 Update NPM Dependencies
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
  hooks/cascading-scans/hook/package-lock.json
  hooks/cascading-scans/hook/package.json
  hooks/notification/hook/package-lock.json
  hooks/notification/hook/package.json
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
  scanners/package-lock.json
  scanners/semgrep/parser/package-lock.json
  tests/integration/package-lock.json
  tests/integration/package.json
Labels: dependencies

#863 Docs: fixes for the nmap scanner documentation
  scanners/nmap/.helm-docs.gotmpl
  scanners/nmap/README.md
  scanners/nmap/docs/README.ArtifactHub.md
  scanners/nmap/docs/README.DockerHub-Parser.md
  scanners/nmap/docs/README.DockerHub-Scanner.md
  scanners/nmap/examples/basic-example/findings.yaml
  scanners/nmap/examples/basic-example/scan.yaml
  scanners/nmap/examples/demo-juice-shop/scan.yaml
  scanners/nmap/examples/demo-target-ssh/findings.yaml
  scanners/nmap/examples/demo-target-ssh/nmap-results.xml
  scanners/nmap/examples/demo-target-ssh/scan.yaml
  scanners/nmap/examples/example-with-parameters/findings.yaml
  scanners/nmap/examples/example-with-parameters/nmap-results.xml
  scanners/nmap/examples/example-with-parameters/scan.yaml
  scanners/nmap/examples/local-network/findings.yaml
  scanners/nmap/examples/local-network/scan.yaml
  scanners/nmap/examples/localhost/findings.yaml
  scanners/nmap/examples/localhost/scan.yaml
Labels: documentation

#881 Brought generated helm-docs temporarily up to date
  hooks/cascading-scans/docs/README.ArtifactHub.md
  hooks/finding-post-processing/docs/README.ArtifactHub.md
  hooks/generic-webhook/docs/README.ArtifactHub.md
  hooks/notification/docs/README.ArtifactHub.md
  hooks/persistence-defectdojo/docs/README.ArtifactHub.md
  hooks/persistence-defectdojo/docs/README.DockerHub-Hook.md
  hooks/persistence-elastic/docs/README.ArtifactHub.md
  hooks/update-field/docs/README.ArtifactHub.md
  scanners/amass/docs/README.ArtifactHub.md
  scanners/angularjs-csti-scanner/docs/README.ArtifactHub.md
  scanners/cmseek/docs/README.ArtifactHub.md
  scanners/cmseek/docs/README.DockerHub-Parser.md
  scanners/cmseek/docs/README.DockerHub-Scanner.md
  scanners/git-repo-scanner/docs/README.ArtifactHub.md
  scanners/git-repo-scanner/docs/README.DockerHub-Parser.md
  scanners/git-repo-scanner/docs/README.DockerHub-Scanner.md
  scanners/gitleaks/docs/README.ArtifactHub.md
  scanners/gitleaks/docs/README.DockerHub-Parser.md
  scanners/gitleaks/docs/README.DockerHub-Scanner.md
  scanners/kube-hunter/docs/README.ArtifactHub.md
  scanners/kube-hunter/docs/README.DockerHub-Parser.md
  scanners/kube-hunter/docs/README.DockerHub-Scanner.md
  scanners/kubeaudit/docs/README.ArtifactHub.md
  scanners/kubeaudit/docs/README.DockerHub-Parser.md
  scanners/kubeaudit/docs/README.DockerHub-Scanner.md
  scanners/ncrack/docs/README.ArtifactHub.md
  scanners/nikto/docs/README.ArtifactHub.md
  scanners/nuclei/docs/README.ArtifactHub.md
  scanners/screenshooter/docs/README.ArtifactHub.md
  scanners/semgrep/docs/README.ArtifactHub.md
  scanners/semgrep/docs/README.DockerHub-Parser.md
  scanners/ssh-scan/docs/README.ArtifactHub.md
  scanners/sslyze/docs/README.ArtifactHub.md
  scanners/test-scan/docs/README.ArtifactHub.md
  scanners/trivy/docs/README.ArtifactHub.md
  scanners/trivy/docs/README.DockerHub-Parser.md
  scanners/typo3scan/docs/README.ArtifactHub.md
  scanners/typo3scan/docs/README.DockerHub-Parser.md
  scanners/typo3scan/docs/README.DockerHub-Scanner.md
  scanners/whatweb/docs/README.ArtifactHub.md
  scanners/whatweb/docs/README.DockerHub-Parser.md
  scanners/whatweb/docs/README.DockerHub-Scanner.md
  scanners/wpscan/docs/README.ArtifactHub.md
  scanners/zap-advanced/docs/README.ArtifactHub.md
  scanners/zap/docs/README.ArtifactHub.md
Labels: maintenance

#866 Add k8s 1.23 to CI Matrix and Update Existing Versions
  .github/workflows/ci.yaml
Labels: dependencies, maintenance

#883 Fix Nuclei ExtraVolumes & Error Case on Single Finding Scans
  scanners/nuclei/parser/__snapshots__/parser.test.js.snap
  scanners/nuclei/parser/__testFiles__/log4j-test.jsonl
  scanners/nuclei/parser/__testFiles__/log4j-test.jsonl.license
  scanners/nuclei/parser/parser.js
  scanners/nuclei/parser/parser.test.js
  scanners/nuclei/templates/nuclei-update-cache-job.yaml
Labels: bug

#889 Added missing helm template definitions
  .templates/new-scanner/.helm-docs.gotmpl
  .templates/new-scanner/README.md
  scanners/cmseek/.helm-docs.gotmpl
  scanners/cmseek/README.md
  scanners/cmseek/docs/README.ArtifactHub.md
  scanners/cmseek/docs/README.DockerHub-Parser.md
  scanners/cmseek/docs/README.DockerHub-Scanner.md
  scanners/typo3scan/.helm-docs.gotmpl
  scanners/typo3scan/README.md
  scanners/typo3scan/docs/README.ArtifactHub.md
  scanners/typo3scan/docs/README.DockerHub-Parser.md
  scanners/typo3scan/docs/README.DockerHub-Scanner.md
  scanners/whatweb/.helm-docs.gotmpl
  scanners/whatweb/README.md
  scanners/whatweb/docs/README.ArtifactHub.md
  scanners/whatweb/docs/README.DockerHub-Parser.md
  scanners/whatweb/docs/README.DockerHub-Scanner.md
Labels: documentation

#882 Added a log4jShell demo-target
  .github/workflows/ci.yaml
  common.mk
  demo-targets/vulnerable-log4j/.helm-docs.gotmpl
  demo-targets/vulnerable-log4j/.helmignore
  demo-targets/vulnerable-log4j/Chart.yaml
  demo-targets/vulnerable-log4j/README.md
  demo-targets/vulnerable-log4j/docs/README.ArtifactHub.md
  demo-targets/vulnerable-log4j/docs/README.DockerHub-Target.md
  demo-targets/vulnerable-log4j/questions.yml
  demo-targets/vulnerable-log4j/templates/NOTES.txt
  demo-targets/vulnerable-log4j/templates/_helpers.tpl
  demo-targets/vulnerable-log4j/templates/deployment.yaml
  demo-targets/vulnerable-log4j/templates/service.yaml
  demo-targets/vulnerable-log4j/templates/tests/test-connection.yaml
  demo-targets/vulnerable-log4j/values.yaml
Labels: testing

#888 Fix Crash in Cascading Hook when using Label Selectors
  hooks/cascading-scans/hook/scan-helpers.ts
Labels: bug

#901 Git Repo Scanner: add archive status to output
  scanners/git-repo-scanner/examples/github-secureCodeBox-scan/findings.yaml
  scanners/git-repo-scanner/scanner/git_repo_scanner/abstract_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner/github_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner/gitlab_scanner.py
  scanners/git-repo-scanner/scanner/tests/git_repo_scanner_test.py
Labels: enhancement, scanner

#891 Fix Missing ttlSecondsAfterFinished in DefectDojo & Finding Post Processing Hook
  hooks/finding-post-processing/templates/finding-post-processing-hook.yaml
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/templates/persistence-provider.yaml
  hooks/persistence-defectdojo/values.yaml
Labels: bug

#886 Made "make docs" POSIX compliant to fix Helm-docs CI issue
  Makefile
Labels: bug
