Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-11, with the labels that each got.

#792 Changed SCB-BOT PR's token to GitHub PAT
  .github/workflows/scb-bot.yaml
Labels: maintenance, ci

#802 Fix Minor Grammar Mistake in Finding Post Processing Hook
  hooks/finding-post-processing/.helm-docs.gotmpl
  hooks/finding-post-processing/README.md
Labels: documentation

#757 Add ability to configure which hooks to run per scan
  hooks/cascading-scans/hook/hook.test.js
  hooks/cascading-scans/hook/hook.ts
  hooks/cascading-scans/hook/kubernetes-label-selector.ts
  hooks/cascading-scans/hook/scan-helpers.ts
  hooks/cascading-scans/templates/cascading-scans-hook.yaml
  hooks/cascading-scans/values.yaml
  hooks/finding-post-processing/templates/finding-post-processing-hook.yaml
  hooks/finding-post-processing/values.yaml
  hooks/generic-webhook/templates/webhook-hook.yaml
  hooks/generic-webhook/values.yaml
  hooks/notification/templates/notification-hook.yaml
  hooks/notification/values.yaml
  hooks/persistence-defectdojo/templates/persistence-provider.yaml
  hooks/persistence-defectdojo/values.yaml
  hooks/persistence-elastic/templates/persistence-provider.yaml
  hooks/persistence-elastic/values.yaml
  hooks/update-field/templates/update-field-hook.yaml
  hooks/update-field/values.yaml
  operator/apis/execution/v1/scan_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/controllers/execution/scans/hook_reconciler.go
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: enhancement, CRD

#801 Add Cronjob Configuration Options and Fix Security Context for Nuclei Chart
  scanners/nuclei/README.md
  scanners/nuclei/templates/nuclei-update-cache-job.yaml
  scanners/nuclei/values.yaml
Labels: bug, enhancement

#695 Add support for hook priorities (ordering)
  hooks/cascading-scans/README.md
  hooks/cascading-scans/hook/hook.test.js
  hooks/cascading-scans/templates/cascading-scans-hook.yaml
  hooks/cascading-scans/values.yaml
  hooks/finding-post-processing/README.md
  hooks/finding-post-processing/templates/finding-post-processing-hook.yaml
  hooks/finding-post-processing/values.yaml
  hooks/generic-webhook/README.md
  hooks/generic-webhook/templates/webhook-hook.yaml
  hooks/generic-webhook/values.yaml
  hooks/notification/README.md
  hooks/notification/templates/notification-hook.yaml
  hooks/notification/values.yaml
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/templates/persistence-provider.yaml
  hooks/persistence-defectdojo/values.yaml
  hooks/persistence-elastic/README.md
  hooks/persistence-elastic/templates/persistence-provider.yaml
  hooks/persistence-elastic/values.yaml
  hooks/update-field/README.md
  hooks/update-field/templates/update-field-hook.yaml
  hooks/update-field/values.yaml
  operator/apis/execution/v1/scan_types.go
  operator/apis/execution/v1/scancompletionhook_types.go
  operator/apis/execution/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/execution.securecodebox.io_scancompletionhooks.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/scan_controller.go
  operator/crds/execution.securecodebox.io_scancompletionhooks.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/utils/orderedhookgroups.go
  operator/utils/orderedhookgroups_test.go
  operator/utils/suite_test.go
Labels: architecture, hook

#798 Add Improvements to SCB Bot
  .github/workflows/scb-bot.yaml
  scanners/amass/Chart.yaml
  scanners/angularjs-csti-scanner/Chart.yaml
  scanners/cmseek/Chart.yaml
  scanners/gitleaks/Chart.yaml
  scanners/kube-hunter/Chart.yaml
  scanners/kubeaudit/Chart.yaml
  scanners/ncrack/Chart.yaml
  scanners/nuclei/Chart.yaml
  scanners/semgrep/Chart.yaml
  scanners/ssh-scan/Chart.yaml
  scanners/sslyze/Chart.yaml
  scanners/trivy/Chart.yaml
  scanners/whatweb/Chart.yaml
  scanners/wpscan/Chart.yaml
  scanners/zap-advanced/Chart.yaml
  scanners/zap/Chart.yaml
Labels: maintenance, testing

#813 Update Helm Docs
  hooks/cascading-scans/README.md
  hooks/finding-post-processing/README.md
  hooks/generic-webhook/README.md
  hooks/notification/README.md
  hooks/persistence-defectdojo/README.md
  hooks/persistence-elastic/README.md
  hooks/update-field/README.md
Labels: documentation

#819 Fixes wrongly appended "v" to the appVersion
  .github/workflows/scb-bot.yaml
Labels: bug

#824 Update Java Model for CRD
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1Scan.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanList.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanSpec.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanSpecCascades.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanSpecCascadesMatchExpressions.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanStatus.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanStatusFindings.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanStatusFindingsSeverities.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanStatusReadAndWriteHookStatus.java
  hooks/persistence-defectdojo/hook/update.sh
Labels: bug

#823 Fixes misformatted upgrade changelog in the SCB bot's generated PR
  .github/workflows/scb-bot.yaml
Labels: bug

#831 Docs: Small fixes for the Typo3Scan documentation
  scanners/typo3scan/.helm-docs.gotmpl
  scanners/typo3scan/README.md
Labels: maintenance, documentation

#835 Docs: Small fixes for the CMSeeK documentation
  scanners/cmseek/.helm-docs.gotmpl
  scanners/cmseek/README.md
Labels: maintenance, documentation

#836 Run kube-hunter As User In Container
  scanners/kube-hunter/scanner/Dockerfile
Labels: scanner, maintenance

#847 Docs: Small fixes for the trivy documentation
  scanners/trivy/.helm-docs.gotmpl
  scanners/trivy/README.md
Labels: documentation

#839 Upgrading Nmap from 7.91-r0 to 7.92-r2
  scanners/nmap/Chart.yaml
  scanners/nmap/parser/__testFiles__/localhost-smb-script.xml
  scanners/nmap/parser/__testFiles__/no-host.xml
  scanners/nmap/parser/__testFiles__/no-ports.xml
  scanners/nmap/parser/__testFiles__/no-service.xml
  scanners/nmap/scanner/Dockerfile
Labels: scanner, dependencies

#848 Docs: Update DefectDojo hook documentation
  hooks/persistence-defectdojo/.helm-docs.gotmpl
  hooks/persistence-defectdojo/README.md
Labels: maintenance, documentation

#829 Docs: Small fixes for the git-repo-scanner documentation
  scanners/git-repo-scanner/.helm-docs.gotmpl
  scanners/git-repo-scanner/README.md
Labels: documentation

#850 Disable SCB-Bot for gitleaks until upgrade to 8.X is complete
  .github/workflows/scb-bot.yaml
Labels: ci
