Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-04, with the labels that each got.

#354 Added missing metadata to ⛑ HelmCharts
  README.md
  hooks/declarative-subsequent-scans/Chart.yaml
  hooks/declarative-subsequent-scans/helm2.Chart.yaml
  hooks/finding-post-processing/Chart.yaml
  hooks/finding-post-processing/helm2.Chart.yaml
  hooks/generic-webhook/Chart.yaml
  hooks/generic-webhook/helm2.Chart.yaml
  hooks/persistence-defectdojo/Chart.yaml
  hooks/persistence-elastic/Chart.yaml
  hooks/persistence-elastic/helm2.Chart.yaml
  hooks/teams-webhook/Chart.yaml
  hooks/teams-webhook/helm2.Chart.yaml
  operator/Chart.yaml
Labels: documentation

#359 Update to JuiceShop v12.6.1
  demo-apps/juice-shop/Chart.yaml
  demo-apps/juice-shop/helm2.Chart.yaml
Labels: dependencies, maintenance

#356 Expanded SSLyze CascadingRules for HTTPS
  scanners/sslyze/cascading-rules/https.yaml
Labels: enhancement

#353 Release And Bugfixing Strategy
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation

#312 Updated GitLeaks to v7.3.0
  .github/workflows/ci.yaml
  scanners/gitleaks/Chart.yaml
  scanners/gitleaks/README.md
  scanners/gitleaks/README.md.gotmpl
  scanners/gitleaks/helm2.Chart.yaml
  scanners/gitleaks/parser/__testFiles__/test-null-report.json
  scanners/gitleaks/parser/parser.js
  scanners/gitleaks/parser/parser.test.js
  scanners/gitleaks/templates/gitleaks-scan-type.yaml
  tests/integration/scanner/gitleaks.test.js
Labels: dependencies

#358 👨‍🏭 Git-Repo-Scanner Refactoring
  .editorconfig
  .github/workflows/ci.yaml
  .gitignore
  scanners/git-repo-scanner/README.md
  scanners/git-repo-scanner/README.md.gotmpl
  scanners/git-repo-scanner/scanner/.dockerignore
  scanners/git-repo-scanner/scanner/Dockerfile
  scanners/git-repo-scanner/scanner/git_repo_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner/__main__.py
  scanners/git-repo-scanner/scanner/git_repo_scanner/abstract_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner/github_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner/gitlab_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner_test.py
  scanners/git-repo-scanner/scanner/requirements.txt
  scanners/git-repo-scanner/scanner/tests/__init__.py
  scanners/git-repo-scanner/scanner/tests/git_repo_scanner_test.py
  scanners/git-repo-scanner/templates/git-repo-scanner-scan-type.yaml
  tests/integration/scanner/git-repo-scanner.test.js
Labels: scanner

#366 Update to JuiceShop v12.7.0
  demo-apps/juice-shop/Chart.yaml
  demo-apps/juice-shop/helm2.Chart.yaml
Labels: dependencies

#367 Fixed HelmChart Hook Templates
  hooks/declarative-subsequent-scans/templates/declerative-subsequent-scans-hook.yaml
  hooks/finding-post-processing/templates/_helpers.tpl
  hooks/finding-post-processing/templates/finding-post-processing-hook.yaml
  hooks/generic-webhook/templates/webhook-hook.yaml
  hooks/persistence-defectdojo/templates/_helpers.tpl
  hooks/persistence-defectdojo/templates/persistence-provider.yaml
  hooks/persistence-elastic/templates/persistence-provider.yaml
  hooks/teams-webhook/templates/teams-hook.yaml
  hooks/update-field/templates/_helpers.tpl
  hooks/update-field/templates/update-field-hook.yaml
Labels: bug

#373 Pins Gradle Version to 6
  hooks/persistence-defectdojo/.dockerignore
  hooks/persistence-defectdojo/Dockerfile
Labels: bug, dependencies

#378 Updated kubeaudit to version v0.13.0
  scanners/kubeaudit/Chart.yaml
  scanners/kubeaudit/helm2.Chart.yaml
Labels: dependencies, scanner

#372 Updated all HelmCharts to v2.7.0-alpha1 to prepare the next SCB release
  demo-apps/bodgeit/Chart.yaml
  demo-apps/bodgeit/helm2.Chart.yaml
  demo-apps/dummy-ssh/Chart.yaml
  demo-apps/dummy-ssh/helm2.Chart.yaml
  demo-apps/http-webhook/Chart.yaml
  demo-apps/juice-shop/Chart.yaml
  demo-apps/juice-shop/helm2.Chart.yaml
  demo-apps/old-wordpress/Chart.yaml
  demo-apps/old-wordpress/helm2.Chart.yaml
  demo-apps/swagger-petstore/Chart.yaml
  demo-apps/swagger-petstore/helm2.Chart.yaml
  demo-apps/unsafe-https/Chart.yaml
  demo-apps/unsafe-https/helm2.Chart.yaml
  hooks/declarative-subsequent-scans/Chart.yaml
  hooks/declarative-subsequent-scans/helm2.Chart.yaml
  hooks/finding-post-processing/Chart.yaml
  hooks/finding-post-processing/helm2.Chart.yaml
  hooks/generic-webhook/Chart.yaml
  hooks/generic-webhook/helm2.Chart.yaml
  hooks/persistence-defectdojo/Chart.yaml
  hooks/persistence-elastic/Chart.yaml
  hooks/persistence-elastic/helm2.Chart.yaml
  hooks/teams-webhook/Chart.yaml
  hooks/teams-webhook/helm2.Chart.yaml
  hooks/update-field/Chart.yaml
  hooks/update-field/helm2.Chart.yaml
  operator/Chart.yaml
  operator/helm2.Chart.yaml
  scanners/amass/Chart.yaml
  scanners/amass/helm2.Chart.yaml
  scanners/angularjs-csti-scanner/Chart.yaml
  scanners/angularjs-csti-scanner/helm2.Chart.yaml
  scanners/git-repo-scanner/Chart.yaml
  scanners/git-repo-scanner/helm2.Chart.yaml
  scanners/gitleaks/Chart.yaml
  scanners/gitleaks/helm2.Chart.yaml
  scanners/kube-hunter/Chart.yaml
  scanners/kube-hunter/helm2.Chart.yaml
  scanners/kubeaudit/Chart.yaml
  scanners/kubeaudit/helm2.Chart.yaml
  scanners/ncrack/Chart.yaml
  scanners/ncrack/helm2.Chart.yaml
  scanners/nikto/Chart.yaml
  scanners/nikto/helm2.Chart.yaml
  scanners/nmap/Chart.yaml
  scanners/nmap/helm2.Chart.yaml
  scanners/screenshooter/Chart.yaml
  scanners/screenshooter/helm2.Chart.yaml
  scanners/ssh-scan/Chart.yaml
  scanners/ssh-scan/helm2.Chart.yaml
  scanners/sslyze/Chart.yaml
  scanners/sslyze/helm2.Chart.yaml
  scanners/test-scan/Chart.yaml
  scanners/test-scan/helm2.Chart.yaml
  scanners/trivy/Chart.yaml
  scanners/trivy/helm2.Chart.yaml
  scanners/wpscan/Chart.yaml
  scanners/wpscan/helm2.Chart.yaml
  scanners/zap/Chart.yaml
  scanners/zap/helm2.Chart.yaml
Labels: dependencies

#376 Added a new OWASP AMASS End-2-End test and fixed AMASS Chart
  .github/workflows/ci.yaml
  scanners/amass/Chart.yaml
  tests/integration/scanner/amass.test.js
Labels: scanner, testing

#377 Updated gitleaks to version v7.4.0
  scanners/gitleaks/Chart.yaml
  scanners/gitleaks/helm2.Chart.yaml
Labels: dependencies, scanner

#370 Upgraded WPScan Scanner to newest version 3.8.17 and added End-2-End test
  .github/workflows/ci.yaml
  scanners/wpscan/Chart.yaml
  scanners/wpscan/README.md
  scanners/wpscan/helm2.Chart.yaml
  scanners/wpscan/values.yaml
  tests/integration/scanner/wpscan.test.js
Labels: dependencies, scanner, testing

#369 Added the tunnel variable from the nmap results to be used in CascadingRules.
  scanners/nmap/parser/parser.js
  scanners/sslyze/cascading-rules/ftps.yaml
  scanners/sslyze/cascading-rules/https.yaml
  scanners/sslyze/cascading-rules/ldaps.yaml
  scanners/sslyze/cascading-rules/mail.yaml
Labels: scanner

#374 Allow wildcards in CascadingRules (closes #357)
  hooks/declarative-subsequent-scans/hook.ts
  hooks/declarative-subsequent-scans/package-lock.json
  hooks/declarative-subsequent-scans/package.json
  scanners/sslyze/cascading-rules/https.yaml
Labels: enhancement, hook

#387 Fix Bug in customTemplate Config of the new Notification Hook
  hooks/notification-hook/notification-templates/slack-individual-findings-with-defectdojo.njk
  hooks/notification-hook/templates/notification-hook.yaml
Labels: bug, hook

#389 Retry Failing Integration Tests up to 3 times
  tests/integration/hooks/finding-post-processing.test.js
  tests/integration/hooks/notification-hook.test.js
  tests/integration/retry.js
  tests/integration/scanner/amass.test.js
  tests/integration/scanner/cascade-nmap-ncrack.test.js
  tests/integration/scanner/cascade-nmap-sslyze.test.js
  tests/integration/scanner/git-repo-scanner.test.js
  tests/integration/scanner/gitleaks.test.js
  tests/integration/scanner/kube-hunter.test.js
  tests/integration/scanner/kubeaudit.test.js
  tests/integration/scanner/ncrack.test.js
  tests/integration/scanner/nikto.test.js
  tests/integration/scanner/nmap.test.js
  tests/integration/scanner/ssh-scan.test.js
  tests/integration/scanner/sslyze.test.js
  tests/integration/scanner/wpscan.test.js
  tests/integration/scanner/zap.test.js
Labels: ci, testing

#380 Add unit test for wildcards in cascading rules
  hooks/declarative-subsequent-scans/hook.test.js
Labels: hook, testing
