Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-09, with the labels that each got.

#592 Integrating new scanner Whatweb to the secureCodeBox (closes #567)
  .github/workflows/ci.yaml
  scanners/whatweb/.helm-docs.gotmpl
  scanners/whatweb/.helmignore
  scanners/whatweb/Chart.yaml
  scanners/whatweb/README.md
  scanners/whatweb/cascading-rules/subdomain.yaml
  scanners/whatweb/docs/.gitkeep
  scanners/whatweb/docs/README.ArtifactHub.md
  scanners/whatweb/docs/README.DockerHub-Parser.md
  scanners/whatweb/docs/README.DockerHub-Scanner.md
  scanners/whatweb/examples/example.com/scan.yaml
  scanners/whatweb/parser/.dockerignore
  scanners/whatweb/parser/Dockerfile
  scanners/whatweb/parser/__testFiles__/example.com.json
  scanners/whatweb/parser/__testFiles__/no-address.com.json
  scanners/whatweb/parser/__testFiles__/securecodebox.io.json
  scanners/whatweb/parser/__testFiles__/two-domains.json
  scanners/whatweb/parser/parser.js
  scanners/whatweb/parser/parser.test.js
  scanners/whatweb/scanner/Dockerfile
  scanners/whatweb/templates/cascading-rules.yaml
  scanners/whatweb/templates/whatweb-parse-definition.yaml
  scanners/whatweb/templates/whatweb-scan-type.yaml
  scanners/whatweb/values.yaml
  tests/integration/scanner/whatweb.test.js
Labels: scanner, testing

#630 Fixing ci workflow whatweb
  .github/workflows/ci.yaml
Labels: bug, ci

#633 Updating cascading-scans hook readme
  hooks/cascading-scans/.helm-docs.gotmpl
  hooks/cascading-scans/README.md
  hooks/cascading-scans/docs/README.ArtifactHub.md
  hooks/cascading-scans/docs/README.DockerHub-Hook.md
Labels: documentation

#636 Added dockerfiles for all demo targets
  demo-targets/bodgeit/container/docker-compose.yml
  demo-targets/dummy-ssh/container/Dockerfile
  demo-targets/dummy-ssh/container/docker-compose.yml
  demo-targets/http-webhook/container/docker-compose.yml
  demo-targets/juice-shop/container/docker-compose.yml
  demo-targets/old-wordpress/container/.ht.sqlite
  demo-targets/old-wordpress/container/Dockerfile
  demo-targets/old-wordpress/container/wp-config.php
  demo-targets/swagger-petstore/container/docker-compose.yml
  demo-targets/unsafe-https/container/Dockerfile
  demo-targets/unsafe-https/container/docker-compose.yml
  demo-targets/unsafe-https/container/index.html
  demo-targets/unsafe-https/container/nginx.conf
  demo-targets/unsafe-https/container/site.crt
  demo-targets/unsafe-https/container/site.key
Labels: testing

#632 Added a Typo3 demo-target
  demo-targets/old-typo3/.helm-docs.gotmpl
  demo-targets/old-typo3/.helmignore
  demo-targets/old-typo3/Chart.yaml
  demo-targets/old-typo3/README.md
  demo-targets/old-typo3/container/Dockerfile
  demo-targets/old-typo3/container/typo3conf/LocalConfiguration.php
  demo-targets/old-typo3/container/typo3conf/PackageStates.php
  demo-targets/old-typo3/container/typo3conf/cms-016d0ef9.sqlite
  demo-targets/old-typo3/questions.yml
  demo-targets/old-typo3/templates/NOTES.txt
  demo-targets/old-typo3/templates/_helpers.tpl
  demo-targets/old-typo3/templates/deployment.yaml
  demo-targets/old-typo3/templates/ingress.yaml
  demo-targets/old-typo3/templates/service.yaml
  demo-targets/old-typo3/templates/tests/test-connection.yaml
  demo-targets/old-typo3/values.yaml
Labels: testing

#635 Upgrade all npm packages with npm audit fix
  hook-sdk/nodejs/package-lock.json
  hooks/cascading-scans/hook/package-lock.json
  hooks/finding-post-processing/hook/package.json
  hooks/generic-webhook/hook/package.json
  hooks/notification/hook/package-lock.json
  hooks/persistence-elastic/hook/package.json
  hooks/update-field/hook/package.json
  parser-sdk/nodejs/package-lock.json
  scanners/nuclei/parser/package-lock.json
  scanners/nuclei/parser/package.json
  tests/integration/package-lock.json
Labels: dependencies, maintenance

#642 Use Multi-Stage-Build For Nikto
  .github/workflows/ci.yaml
  scanners/nikto/scanner/Dockerfile
Labels: enhancement, scanner, maintenance, ci

#645 Fix The Links For WhatWeb To GitHub And Website
  scanners/whatweb/.helm-docs.gotmpl
  scanners/whatweb/README.md
  scanners/whatweb/docs/README.ArtifactHub.md
  scanners/whatweb/docs/README.DockerHub-Parser.md
  scanners/whatweb/docs/README.DockerHub-Scanner.md
Labels: bug, scanner, maintenance, documentation

#643 Update Dependencies
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
  hooks/generic-webhook/hook/package-lock.json
  hooks/generic-webhook/hook/package.json
  hooks/notification/hook/package-lock.json
  hooks/notification/hook/package.json
  hooks/package-lock.json
  hooks/package.json
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
Labels: dependencies

#648 Add cascading rule to Typo3Scan
  scanners/typo3scan/cascading-rules/scan-typo3.yaml
Labels: scanner, cascading-scans

#647 Add integration tests to Typo3Scan
  .github/workflows/ci.yaml
  demo-targets/old-typo3/container/Dockerfile
  tests/integration/scanner/typo3scan.test.js
Labels: scanner, testing

#646 Use proper DefectDojo importer for nuclei and wpscan scans
  hooks/persistence-defectdojo/hook/build.gradle
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/util/ScanNameMapping.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapperTest.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/strategies/VersionedEngagementsStrategyTest.java
Labels: enhancement, defectdojo

#654 Automatically Use Correct Batch Apiversion for Nuclei Cronjob
  scanners/nuclei/templates/nuclei-scan-type.yaml
  scanners/nuclei/templates/nuclei-update-cache-job.yaml
Labels: bug

#658 Adding missing zap-advanced scripts again (closes #656)
  scanners/zap-advanced/.helmignore
  scanners/zap-advanced/scanner/scripts/authentication/scb-oidc-password-grand-type.js
  scanners/zap-advanced/scanner/zapclient/context/zap_context.py
Labels: bug, scanner

#653 Add Pipeline For Release Image Builds
  .github/workflows/release-build.yaml
Labels: maintenance, ci

#660 Update Docker Meta Action
  .github/workflows/ci.yaml
Labels: maintenance, ci

#671 Decrease Number of Expected Trivy Findings within the integration-test
  tests/integration/scanner/trivy.test.js
Labels: testing

#665 Updated `WPScan` scanner to latest release v3.8.19
  scanners/wpscan/Chart.yaml
  scanners/wpscan/README.md
Labels: scanner, dependencies

#670 Updated `trivy` to latest release 0.19.2
  scanners/trivy/Chart.yaml
  scanners/trivy/README.md
Labels: scanner, dependencies

#667 Updated `kubeaudit` to latest release v0.14.2
  scanners/kubeaudit/Chart.yaml
  scanners/kubeaudit/README.md
  scanners/kubeaudit/docs/README.DockerHub-Parser.md
  scanners/kubeaudit/docs/README.DockerHub-Scanner.md
Labels: scanner, dependencies

#669 Updated `nuclei` to latest release v2.5.2
  scanners/nuclei/Chart.yaml
  scanners/nuclei/README.md
  scanners/nuclei/docs/README.DockerHub-Parser.md
Labels: scanner, dependencies

#666 Updated `gitleaks` scanner to latest release v.7.6.1
  scanners/gitleaks/Chart.yaml
  scanners/gitleaks/README.md
  scanners/gitleaks/docs/README.DockerHub-Parser.md
  scanners/gitleaks/docs/README.DockerHub-Scanner.md
  scanners/gitleaks/scanner/Dockerfile
Labels: scanner, dependencies

#673 Fix Defectdojo Hook Issue Causing It to Not Run on Openshift Clusters
  hooks/persistence-defectdojo/hook/Dockerfile
Labels: bug

#675 Align The Makefile For auto-discovery
  auto-discovery/kubernetes/Makefile
Labels: maintenance, auto-discovery

#655 Cache SDK Images As Artifacts
  .github/workflows/ci.yaml
  hook-sdk/nodejs/Makefile
  parser-sdk/nodejs/Makefile
  sdk.mk
Labels: maintenance, ci

#662 Cache Operator and Lurker Images In CI
  .github/workflows/ci.yaml
  operator/Makefile
Labels: maintenance, ci

#678 fix: change indent for .mk files to tab
  .editorconfig
Labels: bug

#677 Add Targets To Build README and Docs
  .github/workflows/helm-docs.yaml
  Makefile
Labels: maintenance

#651 Fix installation scripts
  bin/install.sh
  bin/uninstall.sh
Labels: bug
