Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-06, with the labels that each got.

#464 Add Alternate Slack Notifier using Slack App instead of Webhooks
  hooks/notification-hook/.gitignore
  hooks/notification-hook/NotifierFactory.ts
  hooks/notification-hook/NotifierType.ts
  hooks/notification-hook/Notifiers/AbstractNotifier.ts
  hooks/notification-hook/Notifiers/SlackAppNotifier.test.ts
  hooks/notification-hook/Notifiers/SlackAppNotifier.ts
  hooks/notification-hook/README.md
  hooks/notification-hook/README.md.gotmpl
  hooks/notification-hook/model/NotificationChannel.ts
Labels: enhancement, hook

#465 Switch to Jest official retry mechanism for intergration tests
  bin/npm-audit-fix-all.sh
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
  hooks/declarative-subsequent-scans/package-lock.json
  hooks/declarative-subsequent-scans/package.json
  hooks/finding-post-processing/package-lock.json
  hooks/finding-post-processing/package.json
  hooks/generic-webhook/package-lock.json
  hooks/generic-webhook/package.json
  hooks/notification-hook/package-lock.json
  hooks/notification-hook/package.json
  hooks/package-lock.json
  hooks/package.json
  hooks/persistence-elastic/package-lock.json
  hooks/persistence-elastic/package.json
  hooks/teams-webhook/package-lock.json
  hooks/teams-webhook/package.json
  hooks/update-field/package-lock.json
  hooks/update-field/package.json
  package-lock.json
  package.json
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
  scanners/gitleaks/parser/package-lock.json
  scanners/ncrack/parser/package-lock.json
  scanners/nmap/parser/package-lock.json
  scanners/package-lock.json
  scanners/package.json
  scanners/sslyze/parser/package-lock.json
  scanners/zap/parser/package-lock.json
  tests/integration/generic/no-scan-definition-error.test.js
  tests/integration/generic/read-only-hook.test.js
  tests/integration/generic/read-write-hook.test.js
  tests/integration/hooks/finding-post-processing.test.js
  tests/integration/hooks/notification-hook.test.js
  tests/integration/package-lock.json
  tests/integration/package.json
  tests/integration/retry.js
  tests/integration/scanner/amass.test.js
  tests/integration/scanner/cascade-nmap-ncrack.test.js
  tests/integration/scanner/cascade-nmap-sslyze.test.js
  tests/integration/scanner/git-repo-scanner.test.js
  tests/integration/scanner/gitleaks.test.js
  tests/integration/scanner/kube-hunter.test.js
  tests/integration/scanner/kubeaudit.test.js
  tests/integration/scanner/ncrack.test.js
  tests/integration/scanner/nikto.test.js
  tests/integration/scanner/nmap.test.js
  tests/integration/scanner/ssh-scan.test.js
  tests/integration/scanner/sslyze.test.js
  tests/integration/scanner/wpscan.test.js
  tests/integration/scanner/zap-advanced.test.js
  tests/integration/scanner/zap.test.js
Labels: maintenance, testing

#445 Update shh-scan to 0.0.44
  scanners/ssh-scan/Chart.yaml
  scanners/ssh-scan/README.md
  scanners/ssh-scan/values.yaml
Labels: dependencies, scanner

#468 Add me to the contributors list
  CONTRIBUTORS.md
Labels: maintenance

#467 Make annotations on demo-apps configurable
  demo-apps/bodgeit/README.md
  demo-apps/bodgeit/templates/_helpers.tpl
  demo-apps/bodgeit/templates/deployment.yaml
  demo-apps/bodgeit/templates/service.yaml
  demo-apps/bodgeit/values.yaml
  demo-apps/dummy-ssh/README.md
  demo-apps/dummy-ssh/templates/_helpers.tpl
  demo-apps/dummy-ssh/templates/deployment.yaml
  demo-apps/dummy-ssh/templates/service.yaml
  demo-apps/dummy-ssh/values.yaml
  demo-apps/http-webhook/README.md
  demo-apps/http-webhook/templates/_helpers.tpl
  demo-apps/http-webhook/templates/deployment.yaml
  demo-apps/http-webhook/templates/service.yaml
  demo-apps/http-webhook/values.yaml
  demo-apps/juice-shop/README.md
  demo-apps/juice-shop/templates/_helpers.tpl
  demo-apps/juice-shop/templates/deployment.yaml
  demo-apps/juice-shop/templates/service.yaml
  demo-apps/juice-shop/values.yaml
  demo-apps/old-wordpress/README.md
  demo-apps/old-wordpress/templates/_helpers.tpl
  demo-apps/old-wordpress/templates/deployment.yaml
  demo-apps/old-wordpress/templates/service.yaml
  demo-apps/old-wordpress/values.yaml
  demo-apps/swagger-petstore/README.md
  demo-apps/swagger-petstore/templates/_helpers.tpl
  demo-apps/swagger-petstore/templates/deployment.yaml
  demo-apps/swagger-petstore/templates/service.yaml
  demo-apps/swagger-petstore/values.yaml
  demo-apps/unsafe-https/README.md
  demo-apps/unsafe-https/templates/_helpers.tpl
  demo-apps/unsafe-https/templates/deployment.yaml
  demo-apps/unsafe-https/templates/service.yaml
  demo-apps/unsafe-https/values.yaml
Labels: enhancement

#466 Add make file with test target
  Makefile
  bin/install-npm-test-dependnecies.sh
Labels: maintenance, testing

#422 Include Kubernetes 1.21.1 In Testing/Drop 1.17
  .github/workflows/ci.yaml
Labels: ci, dependencies, testing

#482 Cascading scans codeclimate
  hooks/declarative-subsequent-scans/hook.ts
  hooks/declarative-subsequent-scans/kubernetes-label-selector.test.js
  hooks/declarative-subsequent-scans/kubernetes-label-selector.ts
  hooks/declarative-subsequent-scans/scan-helpers.ts
Labels: maintenance

#481 Cascading Scans: rename directory & docker containers
  .codeclimate.yml
  .eslintignore
  .github/workflows/ci.yaml
  docs/user-guide/README.md
  hooks/cascading-scans/.dockerignore
  hooks/cascading-scans/.gitignore
  hooks/cascading-scans/.helmignore
  hooks/cascading-scans/Chart.lock
  hooks/cascading-scans/Chart.lock.license
  hooks/cascading-scans/Chart.yaml
  hooks/cascading-scans/Dockerfile
  hooks/cascading-scans/README.md
  hooks/cascading-scans/README.md.gotmpl
  hooks/cascading-scans/hook.test.js
  hooks/cascading-scans/hook.ts
  hooks/cascading-scans/kubernetes-label-selector.test.js
  hooks/cascading-scans/kubernetes-label-selector.ts
  hooks/cascading-scans/package-lock.json
  hooks/cascading-scans/package-lock.json.license
  hooks/cascading-scans/package.json
  hooks/cascading-scans/package.json.license
  hooks/cascading-scans/scan-helpers.ts
  hooks/cascading-scans/templates/NOTES.txt
  hooks/cascading-scans/templates/_helpers.tpl
  hooks/cascading-scans/templates/cascading-scans-hook.yaml
  hooks/cascading-scans/templates/role-binding.yaml
  hooks/cascading-scans/templates/role.yaml
  hooks/cascading-scans/templates/service-account.yaml
  hooks/cascading-scans/values.yaml
  hooks/declarative-subsequent-scans/package-lock.json
  hooks/package.json
Labels: breaking, maintenance

#485 Gitleaks: update docs according to new scanner values spec
  scanners/gitleaks/README.md
  scanners/gitleaks/README.md.gotmpl
Labels: documentation

#491 Improve Email Notifier Documentation
  hooks/notification-hook/README.md
  hooks/notification-hook/README.md.gotmpl
Labels: documentation, enhancement

#469 Add `scanner.appendName` to chart values
  scanners/amass/README.md
  scanners/amass/templates/amass-scan-type.yaml
  scanners/amass/values.yaml
  scanners/angularjs-csti-scanner/README.md
  scanners/angularjs-csti-scanner/templates/angularjs-csti-scanner-scan-type.yaml
  scanners/angularjs-csti-scanner/values.yaml
  scanners/git-repo-scanner/README.md
  scanners/git-repo-scanner/templates/git-repo-scanner-scan-type.yaml
  scanners/git-repo-scanner/values.yaml
  scanners/gitleaks/README.md
  scanners/gitleaks/templates/gitleaks-scan-type.yaml
  scanners/gitleaks/values.yaml
  scanners/kube-hunter/README.md
  scanners/kube-hunter/templates/kubehunter-scan-type.yaml
  scanners/kube-hunter/values.yaml
  scanners/kubeaudit/README.md
  scanners/kubeaudit/templates/kubeaudit-scan-type.yaml
  scanners/kubeaudit/values.yaml
  scanners/ncrack/README.md
  scanners/ncrack/templates/ncrack-scan-type.yaml
  scanners/ncrack/values.yaml
  scanners/nikto/README.md
  scanners/nikto/templates/nikto-scan-type.yaml
  scanners/nikto/values.yaml
  scanners/nmap/README.md
  scanners/nmap/README.md.gotmpl
  scanners/nmap/templates/nmap-scan-type.yaml
  scanners/nmap/values.yaml
  scanners/screenshooter/README.md
  scanners/screenshooter/templates/screenshooter-scan-type.yaml
  scanners/screenshooter/values.yaml
  scanners/ssh-scan/README.md
  scanners/ssh-scan/templates/ssh-scan-scan-type.yaml
  scanners/ssh-scan/values.yaml
  scanners/sslyze/README.md
  scanners/sslyze/templates/sslyze-scan-type.yaml
  scanners/sslyze/values.yaml
  scanners/test-scan/README.md
  scanners/test-scan/templates/test-scan-scan-type.yaml
  scanners/test-scan/values.yaml
  scanners/trivy/README.md
  scanners/trivy/templates/trivy-scan-type.yaml
  scanners/trivy/values.yaml
  scanners/wpscan/README.md
  scanners/wpscan/templates/wpscan-scan-type.yaml
  scanners/wpscan/values.yaml
  scanners/zap-advanced/README.md
  scanners/zap-advanced/templates/zap-advanced-scan-type.yaml
  scanners/zap-advanced/values.yaml
  scanners/zap/README.md
  scanners/zap/templates/zap-scan-type.yaml
  scanners/zap/values.yaml
Labels: breaking, maintenance

#486 Add Notification Channel Option to Skip Notifications on Zero Findings
  CONTRIBUTORS.md
  hooks/notification-hook/README.md
  hooks/notification-hook/README.md.gotmpl
  hooks/notification-hook/hook.test.ts
  hooks/notification-hook/hook.ts
  hooks/notification-hook/model/NotificationChannel.ts
  hooks/notification-hook/package-lock.json
  hooks/notification-hook/package.json
Labels: enhancement

#498 Document how to certify our DCO
  CONTRIBUTING.md
Labels: documentation

#501 Fix Find Command to Install NPM Dependencies
  Makefile
Labels: bug

#497 Make Helm Docs Bot Signoff Its Commits
  .github/workflows/helm-docs.yaml
Labels: ci

#503 [v3] Fix Find Command to Install NPM Dependencies
  Makefile
Labels: bug

#496 Added Documentation on How-To run DefectDojo Hook Locally
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/README.md.gotmpl
Labels: defectdojo, documentation

#484 Refactor hook HelmCharts to introduce consistency in HelmChart Values
  .github/workflows/ci.yaml
  hooks/cascading-scans/README.md
  hooks/cascading-scans/templates/cascading-scans-hook.yaml
  hooks/cascading-scans/values.yaml
  hooks/finding-post-processing/README.md
  hooks/finding-post-processing/templates/finding-post-processing-hook.yaml
  hooks/finding-post-processing/values.yaml
  hooks/generic-webhook/README.md
  hooks/generic-webhook/templates/webhook-hook.yaml
  hooks/generic-webhook/values.yaml
  hooks/notification/README.md
  hooks/notification/templates/notification-hook.yaml
  hooks/notification/values.yaml
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/templates/persistence-provider.yaml
  hooks/persistence-defectdojo/values.yaml
  hooks/persistence-elastic/README.md
  hooks/persistence-elastic/templates/persistence-provider.yaml
  hooks/persistence-elastic/values.yaml
  hooks/teams-webhook/README.md
  hooks/teams-webhook/README.md.gotmpl
  hooks/teams-webhook/templates/teams-hook.yaml
  hooks/teams-webhook/values.yaml
  hooks/update-field/README.md
  hooks/update-field/templates/update-field-hook.yaml
  hooks/update-field/values.yaml
  tests/integration/hooks/__testFiles__/finding-post-processing-values.yaml
  tests/integration/hooks/__testFiles__/notification-values.yaml
Labels: breaking, hook, maintenance

#517 Remove ssh_scan Workaround
  bin/install.sh
  bin/uninstall.sh
Labels: maintenance

#516 Added documentation on how to run the Parser-SDK locally
  parser-sdk/nodejs/README.md
Labels: documentation

#492 Added Timestamps to Findings JSON File
  parser-sdk/nodejs/parser-wrapper.js
Labels: enhancement

#521 Minor Maintenance Fixes for ZAP Advanced ScanType
  scanners/zap-advanced/examples/demo-bodgeit-scan-authenticated/scan.yaml
  scanners/zap-advanced/examples/demo-bodgeit-scan-unauthenticated/scan.yaml
  scanners/zap-advanced/examples/demo-juiceshop-scan-authenticated/scan.yaml
  scanners/zap-advanced/examples/demo-juiceshop-scan-unauthenticated/scan.yaml
  scanners/zap-advanced/examples/demo-petstoreapi-scan-authenticated/scan.yaml
  scanners/zap-advanced/examples/demo-petstoreapi-scan-unauthenticated/scan.yaml
  scanners/zap-advanced/examples/secureCodeBox.io-scan/scan.yaml
  scanners/zap-advanced/templates/zap-advanced-scan-type.yaml
Labels: documentation, maintenance

#487 Added DefectDojo Hook Support for all secureCodeBox Scanners
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/DefectDojoPersistenceProvider.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapper.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapper.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/models/DefectDojoImportFinding.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/models/SecureCodeBoxFinding.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/service/KubernetesService.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/service/S3Service.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/service/ScanService.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/strategies/VersionedEngagementsStrategy.java
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/util/ScanNameMapping.java
  hooks/persistence-defectdojo/src/test/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapperTest.java
  hooks/persistence-defectdojo/src/test/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapperTest.java
  hooks/persistence-defectdojo/src/test/java/io/securecodebox/persistence/service/KubernetesServiceTest.java
  hooks/persistence-defectdojo/src/test/resources/kubehunter-dd-findings.json
  hooks/persistence-defectdojo/src/test/resources/kubehunter-scb-findings.json
Labels: defectdojo, enhancement, hook, persistence
