Repository secureCodeBox/secureCodeBox, pull requests merged in 2021-07, with the labels that each got.

#526 Run gitleaks As User In Container
  scanners/gitleaks/scanner/Dockerfile
  scanners/gitleaks/scanner/wrapper.sh
Labels: maintenance, scanner

#527 Run git-repo-scanner As User
  scanners/git-repo-scanner/scanner/Dockerfile
Labels: maintenance, scanner

#529 Fixed Bug in DefectDojo Hook where Findings with Null fields caused Runtime Exceptions
  hooks/persistence-defectdojo/src/main/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapper.java
  hooks/persistence-defectdojo/src/test/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapperTest.java
Labels: bug

#530 Fix Bug Preventing `skipNotificationOnZeroFindings` from Working Correctly
  hooks/notification-hook/hook.ts
Labels: backport, bug

#531 Use filtered findings for check instead of the original
  hooks/notification/hook.ts
Labels: bug

#514 Add matched-finding id to cascading scan annotations
  hooks/cascading-scans/hook.test.js
  hooks/cascading-scans/hook.ts
  hooks/cascading-scans/scan-helpers.ts
Labels: enhancement, scanner

#425 Improve install/uninstall script to respect namespaces
  bin/install.sh
  bin/uninstall.sh
Labels: maintenance

#537 Rename lurcher to lurker
  .github/workflows/ci.yaml
  docs/resources/scb-architecture.drawio
  docs/resources/scb-architecture.svg
  docs/uml/compononents_overview.uxf
  docs/uml/sequence_overview.puml
  lurker/.dockerignore
  lurker/.gitignore
  lurker/Dockerfile
  lurker/docs/README.DockerHub-Core.md
  lurker/go.mod
  lurker/go.sum
  lurker/go.sum.license
  lurker/main.go
  operator/Chart.yaml
  operator/README.md
  operator/controllers/execution/scans/scan_controller.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/docs/README.ArtifactHub.md
  operator/templates/manager/manager.yaml
  operator/values.yaml
  scanners/angularjs-csti-scanner/scanner/wrapper.sh
  scanners/kubeaudit/templates/kubeaudit-rbac.yaml
  scanners/screenshooter/scanner/wrapper.sh
Labels: breaking, maintenance

#548 Update NPM Dependencies
  hooks/cascading-scans/package-lock.json
  hooks/cascading-scans/package.json
  hooks/finding-post-processing/package-lock.json
  hooks/finding-post-processing/package.json
  hooks/generic-webhook/package-lock.json
  hooks/generic-webhook/package.json
  hooks/notification/package-lock.json
  hooks/notification/package.json
  hooks/package-lock.json
  hooks/package.json
  hooks/persistence-elastic/package-lock.json
  hooks/persistence-elastic/package.json
  hooks/teams-webhook/package-lock.json
  hooks/teams-webhook/package.json
  hooks/update-field/package-lock.json
  hooks/update-field/package.json
  package-lock.json
  package.json
  scanners/package-lock.json
  scanners/package.json
Labels: dependencies, maintenance

#555 Upgrade `ws` And `@kubernetes/client-node`
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
Labels: dependencies, maintenance

#556 Fix inconsistent casing in findings created in DefectDojo Hooks `syncFindingsBack` Mode
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapper.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/models/SecureCodeBoxFinding.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/service/KubernetesService.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapperTest.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/SecureCodeBoxFindingsToDefectDojoMapperTest.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/service/KubernetesServiceTest.java
  hooks/persistence-defectdojo/hook/src/test/resources/kubehunter-dd-findings.json
Labels: bug, defectdojo, hook

#538 Inherit environment variables, volumes, and volume mounts from parent scan
  hooks/cascading-scans/hook/hook.test.js
  hooks/cascading-scans/hook/hook.ts
  hooks/cascading-scans/hook/scan-helpers.ts
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapperTest.java
  operator/apis/execution/v1/scan_types.go
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: cascading-scans, enhancement

#542 Propose ADR to drop documentation versioning
  docs/adr/adr_0008.md
Labels: architecture, documentation

#559 Add Dedicated User For Screenshooter
  scanners/screenshooter/scanner/Dockerfile
Labels: maintenance, scanner

#561 Update kube-hunter from 0.4.1 -> 0.6.1
  scanners/kube-hunter/Chart.yaml
  scanners/kube-hunter/README.md
  scanners/kube-hunter/docs/README.DockerHub-Parser.md
  scanners/kube-hunter/docs/README.DockerHub-Scanner.md
Labels: dependencies, maintenance, scanner

#551 Add Makefile For Amass
  .github/workflows/ci.yaml
  operator/Makefile
  scanners/amass/.gitignore
  scanners/amass/.helmignore
  scanners/amass/Makefile
  scanners/amass/integration-tests/amass.test.js
  scanners/amass/integration-tests/jest.config.json
  scanners/amass/parser/jest.config.json
Labels: ci, maintenance, scanner

#564 Update WS, JEST and @kubernetes/client-node
  bin/npm-check-updates.sh
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
Labels: dependencies, maintenance

#560 Add Dedicated Container User For ncrack
  scanners/ncrack/scanner/Dockerfile
Labels: maintenance, scanner

#565 This accepts ADR 8
  docs/adr/adr_0008.md
Labels: documentation

#562 Add Alert Filters Config to ZAP Advanced
  scanners/zap-advanced/examples/nginx/0-foo.yaml
  scanners/zap-advanced/scanner/tests/mocks/scan-full-petstore-alert-filter-docker/1_zap-advanced-scan-config.yaml
  scanners/zap-advanced/scanner/tests/test_integration_docker_local.py
  scanners/zap-advanced/scanner/zapclient/context/zap_context.py
Labels: enhancement, scanner
