Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-05, with the labels that each got.

#1154 Removed module type from hooks/package.json
  hooks/package.json
Labels: bug

#1157 Add SSLyze Image to custom scanner list
  .github/workflows/release-build.yaml
Labels: bug

#1143 Allows the Dashboard importer to be built through the makefiles
  .github/workflows/ci.yaml
  hooks/persistence-elastic/Makefile
  hooks/persistence-elastic/dashboard-importer/Dockerfile
  hooks/persistence-elastic/dashboard-importer/dashboards/daily-summary.json
  hooks/persistence-elastic/dashboard-importer/dashboards/daily-summary.json.license
  hooks/persistence-elastic/dashboard-importer/dashboards/nikto-overview.json
  hooks/persistence-elastic/dashboard-importer/dashboards/nikto-overview.json.license
  hooks/persistence-elastic/dashboard-importer/dashboards/portscan-overview.json
  hooks/persistence-elastic/dashboard-importer/dashboards/portscan-overview.json.license
  hooks/persistence-elastic/dashboard-importer/dashboards/ssh-overview.json
  hooks/persistence-elastic/dashboard-importer/dashboards/ssh-overview.json.license
  hooks/persistence-elastic/dashboard-importer/dashboards/subdomain-overview.json
  hooks/persistence-elastic/dashboard-importer/dashboards/subdomain-overview.json.license
  hooks/persistence-elastic/dashboard-importer/dashboards/tls-ssl-overview.json
  hooks/persistence-elastic/dashboard-importer/dashboards/tls-ssl-overview.json.license
  hooks/persistence-elastic/dashboard-importer/dashboards/wordpress-overview.json
  hooks/persistence-elastic/dashboard-importer/dashboards/wordpress-overview.json.license
  hooks/persistence-elastic/dashboard-importer/dashboards/zap-overview.json
  hooks/persistence-elastic/dashboard-importer/dashboards/zap-overview.json.license
  hooks/persistence-elastic/dashboard-importer/export-dashboards.sh
  hooks/persistence-elastic/dashboard-importer/import-dashboards.sh
  hooks/persistence-elastic/dashboard-importer/readme.md
Labels: bug, planned

#1153 New Trello type for the notification hook
  CONTRIBUTORS.md
  hooks/notification/docs/README.ArtifactHub.md
  hooks/notification/hook/NotifierFactory.test.ts
  hooks/notification/hook/NotifierFactory.ts
  hooks/notification/hook/NotifierType.ts
  hooks/notification/hook/Notifiers/TrelloNotifier.test.ts
  hooks/notification/hook/Notifiers/TrelloNotifier.ts
  hooks/notification/hook/__testfiles__/trello.json
  hooks/notification/hook/hook.test.ts
  hooks/notification/hook/model/Finding.ts
Labels: enhancement, hook

#1166 Regenerate Helm Docs
  hooks/notification/.helm-docs.gotmpl
  hooks/notification/README.md
  hooks/notification/docs/README.ArtifactHub.md
Labels: bug, documentation

#1168 Add Multi-Platform Builds for ARM Container Images
  .github/workflows/release-build.yaml
  .yamllint.yaml
  auto-discovery/kubernetes/Dockerfile
  hooks/persistence-azure-monitor/hook/Dockerfile
  lurker/Dockerfile
  operator/Dockerfile
  scanners/angularjs-csti-scanner/Chart.yaml
  scanners/cmseek/Chart.yaml
  scanners/cmseek/parser/Dockerfile
  scanners/kube-hunter/Chart.yaml
  scanners/kubeaudit/Chart.yaml
  scanners/ncrack/Chart.yaml
  scanners/nikto/Chart.yaml
  scanners/nmap/Chart.yaml
  scanners/semgrep/parser/Dockerfile
  scanners/sslyze/Chart.yaml
  scanners/typo3scan/Chart.yaml
  scanners/typo3scan/parser/Dockerfile
  scanners/whatweb/Chart.yaml
Labels: enhancement, ci

#1176 Update Various Go Package
  auto-discovery/kubernetes/Dockerfile
  auto-discovery/kubernetes/go.mod
  auto-discovery/kubernetes/go.sum
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_parsedefinitions.yaml
  operator/config/crd/bases/execution.securecodebox.io_scancompletionhooks.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scantypes.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_parsedefinitions.yaml
  operator/crds/execution.securecodebox.io_scancompletionhooks.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scantypes.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
  operator/go.mod
  operator/go.sum
  operator/utils/hash_test.go
Labels: dependencies

#1182 Fixed the path for dashboard-importer in release-build.yaml
  .github/workflows/release-build.yaml
Labels: bug

#1186 Fix documented values for resourceInclusion modes
  auto-discovery/kubernetes/.helm-docs.gotmpl
  auto-discovery/kubernetes/README.md
  auto-discovery/kubernetes/docs/README.ArtifactHub.md
Labels: bug, documentation
