Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-02, with the labels that each got.

#944 Helm - Juice Shop - Custom environment variables and application config.yml
  demo-targets/juice-shop/Chart.yaml
  demo-targets/juice-shop/templates/configmap.yaml
  demo-targets/juice-shop/templates/deployment.yaml
  demo-targets/juice-shop/values.yaml
Labels: enhancement

#950 Improve Makefiles for generating scanner documentation
  .github/workflows/helm-docs.yaml
  Makefile
  bin/generate-scanner-docs.sh
  demo-targets/juice-shop/README.md
  demo-targets/juice-shop/docs/README.ArtifactHub.md
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/docs/README.ArtifactHub.md
  scanners/nuclei/README.md
  scanners/nuclei/docs/README.ArtifactHub.md
Labels: enhancement

#954 Improve Makefiles for generating other documentation
  .github/workflows/helm-docs.yaml
  .github/workflows/scb-bot.yaml
  Makefile
  bin/generate-docs.sh
  bin/generate-scanner-docs.sh
Labels: bug

#955 Upgrade SCB-Bot helm-docs version to 1.6.0
  .github/workflows/scb-bot.yaml
Labels: maintenance

#982 Update npm deps
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
  hooks/cascading-scans/hook/package-lock.json
  hooks/cascading-scans/hook/package.json
  hooks/generic-webhook/hook/package-lock.json
  hooks/notification/hook/package-lock.json
  hooks/notification/hook/package.json
  hooks/package-lock.json
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
  scanners/package-lock.json
  tests/integration/package-lock.json
  tests/integration/package.json
Labels: maintenance

#668 Updated `nikto` to latest release v2.5.0
  scanners/nikto/Chart.yaml
  scanners/nikto/README.md
  scanners/nikto/examples/demo-bodgeit/findings.yaml
  scanners/nikto/examples/demo-bodgeit/nikto-results.json
  scanners/nikto/examples/demo-bodgeit/scan.yaml
  scanners/nikto/examples/demo-docs.securecodebox.io/scan.yaml
  scanners/nikto/examples/demo-juice-shop/findings.yaml
  scanners/nikto/examples/demo-juice-shop/nikto-results.json
  scanners/nikto/examples/demo-juice-shop/scan.yaml
  scanners/nikto/integration-tests/nikto.test.js
  scanners/nikto/parser/__snapshots__/parser.test.js.snap
  scanners/nikto/parser/__testFiles__/docs.securecodebox.io.json
  scanners/nikto/parser/__testFiles__/docs.securecodebox.io.json.license
  scanners/nikto/parser/__testFiles__/juice-shop.json
  scanners/nikto/parser/__testFiles__/unresolvable-host.json
  scanners/nikto/parser/__testFiles__/unresolvable-host.json.license
  scanners/nikto/parser/__testFiles__/www.securecodebox.io.json
  scanners/nikto/parser/parser.test.js
Labels: scanner, dependencies

#903 Git Repo Scanner: Add repository topics to output
  scanners/git-repo-scanner/examples/github-secureCodeBox-scan/findings.yaml
  scanners/git-repo-scanner/scanner/git_repo_scanner/abstract_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner/github_scanner.py
  scanners/git-repo-scanner/scanner/git_repo_scanner/gitlab_scanner.py
  scanners/git-repo-scanner/scanner/tests/git_repo_scanner_test.py
Labels: enhancement, scanner

#986 Trigger CI pipeline nightly build with zap-advanced tests
  .github/workflows/ci.yaml
Labels: testing

#987 Remove codeclimate from PR template checklist
  .github/pull_request_template.md
Labels: maintenance

#843 documentation of ncrack sample corrected (refactoring of 'scannerJob'…
  UPGRADING.md
  scanners/ncrack/.helm-docs.gotmpl
  scanners/ncrack/README.md
  scanners/ncrack/docs/README.ArtifactHub.md
Labels: documentation

#959 Refactor Makefile and Docs Script to Reduce Code Duplication
  Makefile
  bin/generate-docs.sh
  bin/generate-helm-docs.sh
Labels: enhancement

#988 Add our Helm repo in install script
  bin/install.sh
Labels: bug

#993 Added cmseek to the release pipeline again to fix broken HelmChart
  .github/workflows/release-build.yaml
Labels: bug, scanner

#992 Added requirement to MarkupSafe to version 2.0.1
  scanners/zap-advanced/scanner/requirements.txt
Labels: bug, testing

#994 Restore scantype-configMap.yaml to fix zap-advacned integration-test
  .github/workflows/ci.yaml
  scanners/zap-advanced/integration-test/scantype-configMap.yml
Labels: bug, testing, ci

#983 Added Scantype-Controller Test to test the RetriggerOnScanTypeChange Flag
  operator/controllers/execution/scantype_controller_test.go
  operator/controllers/execution/test_utils_test.go
Labels: testing

#913 Add Azure Monitor persistence hook
  .github/workflows/ci.yaml
  hooks/persistence-azure-monitor/.helm-docs.gotmpl
  hooks/persistence-azure-monitor/.helmignore
  hooks/persistence-azure-monitor/Chart.yaml
  hooks/persistence-azure-monitor/Makefile
  hooks/persistence-azure-monitor/README.md
  hooks/persistence-azure-monitor/docs/README.ArtifactHub.md
  hooks/persistence-azure-monitor/docs/README.DockerHub-Hook.md
  hooks/persistence-azure-monitor/hook/Dockerfile
  hooks/persistence-azure-monitor/hook/__snapshots__/hook.test.js.snap
  hooks/persistence-azure-monitor/hook/hook.js
  hooks/persistence-azure-monitor/hook/hook.test.js
  hooks/persistence-azure-monitor/hook/package-lock.json
  hooks/persistence-azure-monitor/hook/package-lock.json.license
  hooks/persistence-azure-monitor/hook/package.json
  hooks/persistence-azure-monitor/hook/package.json.license
  hooks/persistence-azure-monitor/templates/NOTES.txt
  hooks/persistence-azure-monitor/templates/_helpers.tpl
  hooks/persistence-azure-monitor/templates/persistence-provider.yaml
  hooks/persistence-azure-monitor/values.yaml
Labels: enhancement, persistence, hook

#1002 ZapAdvanced Enforced Spider Timeouts
  scanners/zap-advanced/scanner/zapclient/spider/zap_abstract_spider.py
  scanners/zap-advanced/scanner/zapclient/spider/zap_spider_ajax.py
  scanners/zap-advanced/scanner/zapclient/spider/zap_spider_http.py
Labels: enhancement, scanner
