Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-04, with the labels that each got.

#1086 Update OWASP Project Maturaty Level
  README.md
Labels: documentation

#1085 Update Trivy Command used in Kubernetes Container AutoDiscovery
  auto-discovery/kubernetes/README.md
  auto-discovery/kubernetes/auto-discovery-config.yaml
  auto-discovery/kubernetes/docs/README.ArtifactHub.md
  auto-discovery/kubernetes/values.yaml
Labels: bug, auto-discovery

#1089 Removed ´Unit-Tests | JavaScript´ and ´Unit-Tests | Python´ jobs from CI
  .github/workflows/ci.yaml
Labels: maintenance, planned

#1091 Embedd Original (Non Duplicate) Finding in DefectDojo Hooks SyncBack Duplicate Findings
  hooks/persistence-defectdojo/.helm-docs.gotmpl
  hooks/persistence-defectdojo/README.md
  hooks/persistence-defectdojo/docs/README.ArtifactHub.md
  hooks/persistence-defectdojo/hook/build.gradle
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/DefectDojoPersistenceProvider.java
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapper.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapperTest.java
Labels: enhancement, defectdojo

#1097 Fix markdown issues in ZAP-advanced docs
  scanners/zap-advanced/.helm-docs.gotmpl
  scanners/zap-advanced/README.md
  scanners/zap-advanced/docs/README.ArtifactHub.md
Labels: documentation

#1070 Kubernetes Service AutoDiscovery: Automatically delete ScheduledScans when Scanned Service is Deleted
  auto-discovery/kubernetes/controllers/service_scan_controller.go
Labels: bug, auto-discovery

#1073 Fixes cascading scan hook integration tests
  .github/workflows/ci.yaml
  hooks/cascading-scans/Makefile
  hooks/cascading-scans/hook/integration-tests/cascade-nmap-ncrack.test.js
  hooks/cascading-scans/hook/integration-tests/cascade-nmap-sslyze.test.js.disabled
  hooks/cascading-scans/hook/package-lock.json
  hooks/cascading-scans/hook/package.json
  hooks/package-lock.json
  hooks/package.json
  tests/integration/package-lock.json
  tests/integration/package.json
Labels: testing, planned

#1102 Improved the local makefile workflow
  Makefile
  common.mk
  env-paths.mk
  hooks.mk
  scanners.mk
  sdk.mk
Labels: testing, planned

#1123 Added a CI trigger on Pull request
  .github/workflows/ci.yaml
Labels: testing

#1111 Reduced the number of relative paths in the Makefiles
  auto-discovery/kubernetes/Makefile
  common.mk
  hooks.mk
  hooks/cascading-scans/Makefile
  operator/Makefile
  scanners.mk
  scanners/gitleaks/Makefile
  scanners/semgrep/Makefile
  scanners/test-scan/Makefile
  scanners/zap-advanced/Makefile
  sdk.mk
Labels: testing

#1107 Feature/authenticated generic webhook
  CONTRIBUTORS.md
  hooks/generic-webhook/hook/hook.js
  hooks/generic-webhook/templates/webhook-hook.yaml
  hooks/generic-webhook/values.yaml
Labels: hook

#1138 Regenerate Docs (Didn't get generated for Exteral PR)
  hooks/generic-webhook/README.md
  hooks/generic-webhook/docs/README.ArtifactHub.md
Labels: bug, documentation, skip-changelog

#1124 Removed the simply expanded variable for the ABS_PROJECT_DIR in Makefile
  auto-discovery/kubernetes/Makefile
  operator/Makefile
Labels: testing, planned

#1133 Make common.mk use python3 (new) (Closes #1019)
  common.mk
  scanners/git-repo-scanner/Makefile
Labels: bug, python, planned
