Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-11, with the labels that each got.

#1427 Docs: Make separation between cluster- and namespace modes more explicit in ADR12 (Cluster-wide resources)
  docs/adr/adr_0012.md
Labels: documentation, architecture

#1429 Fix duplicate title of adr 5 and 6
  docs/adr/adr_0006.md
Labels: documentation

#1437 fix(ci): Only allow helm-docs and scb-bot workflows to run on the non-fork repo
  .github/workflows/helm-docs.yaml
  .github/workflows/scb-bot.yaml
Labels: bug

#1409 [Snyk] Upgrade ws from 8.8.1 to 8.9.0
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
Labels: dependencies

#1329 Auto discovery consistent behavior
  UPGRADING.md
  auto-discovery/kubernetes/README.md
  auto-discovery/kubernetes/api/v1/autodiscoveryconfig_types.go
  auto-discovery/kubernetes/api/v1/zz_generated.deepcopy.go
  auto-discovery/kubernetes/auto-discovery-config.yaml
  auto-discovery/kubernetes/controllers/container_scan_controller.go
  auto-discovery/kubernetes/controllers/container_scan_controller_test.go
  auto-discovery/kubernetes/controllers/suite_test.go
  auto-discovery/kubernetes/docs/README.ArtifactHub.md
  auto-discovery/kubernetes/values.yaml
Labels: maintenance, breaking, hacktoberfest-accepted

#1398 Fix / Upgrade `controller-tools` Version in Make Files
  auto-discovery/kubernetes/Makefile
  auto-discovery/kubernetes/controllers/suite_test.go
  operator/Makefile
  operator/controllers/execution/suite_test.go
Labels: maintenance, hacktoberfest-accepted

#1444 [Snyk] Upgrade ws from 8.9.0 to 8.10.0
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
Labels: dependencies

#1448 Also run the CI for our release branches
  .github/workflows/ci.yaml
Labels: bug

#1451 [Snyk] Upgrade ws from 8.9.0 to 8.10.0
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
Labels: dependencies

#1450 Remove codeclimate yaml and badges from readme
  .codeclimate.yml
  README.md
Labels: skip-changelog

#1457 Formulate Reasons for Move S3 in ADR
  docs/adr/adr_0015.md
  docs/adr/adr_0016.md
Labels: documentation

#1462 Fix semgrep helm linting error
  CONTRIBUTORS.md
  scanners/semgrep/Chart.yaml
Labels: bug
