Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-12, with the labels that each got.

#1461 Deprecate ADR-0005
  docs/adr/adr_0000.md
  docs/adr/adr_0005.md
  docs/adr/adr_0006.md
  docs/adr/adr_0007.md
Labels: documentation

#1483 NPM audit fix
  hook-sdk/nodejs/package-lock.json
  hooks/finding-post-processing/hook/package-lock.json
  hooks/generic-webhook/hook/package-lock.json
  hooks/notification/hook/package-lock.json
  hooks/persistence-azure-monitor/hook/package-lock.json
  hooks/persistence-elastic/hook/package-lock.json
  hooks/update-field-hook/hook/package-lock.json
  package-lock.json
  parser-sdk/nodejs/package-lock.json
  scanners/package-lock.json
  tests/integration/package-lock.json
Labels: maintenance

#1490 #1458 Reject ADR-0006 because noone cares about versioned documentation
  docs/adr/adr_0006.md
Labels: documentation

#1426 Docs: Update ADR14 with results from discussion
  docs/adr/adr_0014.md
Labels: documentation, architecture

#1315 Integrate ZAP Automation Framework (closes #1188)
  CONTRIBUTORS.md
  scanners/zap/.helm-docs.gotmpl
  scanners/zap/Makefile
  scanners/zap/examples/demo-nginx-automation-scan/findings.yaml
  scanners/zap/examples/demo-nginx-automation-scan/scan.yaml
  scanners/zap/examples/demo-nginx-automation-scan/zap-results.json
  scanners/zap/examples/demo-nginx-automation-scan/zap-results.json.license
  scanners/zap/integration-tests/automation-framework-configMap.yaml
  scanners/zap/integration-tests/zap.test.js
  scanners/zap/parser/parser.test.js
  scanners/zap/templates/zap-scan-type.yaml
Labels: enhancement, scanner, hacktoberfest-accepted

#1390 new scanner ffuf (closes #1319)
  .github/workflows/ci.yaml
  .github/workflows/release-build.yaml
  .github/workflows/scb-bot.yaml
  scanners/ffuf/.gitignore
  scanners/ffuf/.helm-docs.gotmpl
  scanners/ffuf/.helmignore
  scanners/ffuf/Chart.yaml
  scanners/ffuf/Makefile
  scanners/ffuf/README.md
  scanners/ffuf/cascading-rules/http.yaml
  scanners/ffuf/docs/.gitkeep
  scanners/ffuf/docs/README.ArtifactHub.md
  scanners/ffuf/docs/README.DockerHub-Parser.md
  scanners/ffuf/docs/README.DockerHub-Scanner.md
  scanners/ffuf/examples/wordlist-config-map-multiple-fuzz-keywords/scan.yaml
  scanners/ffuf/examples/wordlist-config-map-multiple-fuzz-keywords/wordlist.txt
  scanners/ffuf/examples/wordlist-config-map-post/scan.yaml
  scanners/ffuf/examples/wordlist-config-map-post/wordlistPasswords.txt
  scanners/ffuf/examples/wordlist-config-map-post/wordlistUsernames.txt
  scanners/ffuf/examples/wordlist-config-map/scan.yaml
  scanners/ffuf/examples/wordlist-config-map/wordlist.txt
  scanners/ffuf/integration-tests/configmap-wordlist.yaml
  scanners/ffuf/integration-tests/ffuf.test.js
  scanners/ffuf/integration-tests/jest.config.json
  scanners/ffuf/parser/.dockerignore
  scanners/ffuf/parser/Dockerfile
  scanners/ffuf/parser/__testFiles__/empty.json
  scanners/ffuf/parser/__testFiles__/ffuf-results-multiple-fuzz-keywords.json
  scanners/ffuf/parser/__testFiles__/ffuf-results-postdata.json
  scanners/ffuf/parser/__testFiles__/ffuf-results.json
  scanners/ffuf/parser/__testFiles__/zeroFindings.json
  scanners/ffuf/parser/package-lock.json
  scanners/ffuf/parser/package.json
  scanners/ffuf/parser/parser.js
  scanners/ffuf/parser/parser.test.js
  scanners/ffuf/scanner/Dockerfile
  scanners/ffuf/templates/cascading-rules.yaml
  scanners/ffuf/templates/ffuf-parse-definition.yaml
  scanners/ffuf/templates/ffuf-scan-type.yaml
  scanners/ffuf/values.yaml
Labels: scanner, hacktoberfest-accepted

#1500 Change log level for json authentication log (closes #1497)
  CONTRIBUTORS.md
  scanners/zap-advanced/scanner/zapclient/context/zap_context_authentication.py
Labels: bug

#1380 Add option to specifiy presigned url duration validity
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_controller.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/templates/manager/manager.yaml
  operator/utils/url_expiration_duration.go
  operator/values.yaml
Labels: enhancement, planned, hacktoberfest-accepted

#1374 ADR 17: Enable container autodiscovery to scan images from private repos
  docs/adr/adr_0017.md
Labels: architecture, auto-discovery, hacktoberfest-accepted

#1502 Add Upgrading Notes for Nuclei Findings
  UPGRADING.md
Labels: documentation

#1509 fix(scb-bot): Adds error handling to remote version fetching
  .github/workflows/scb-bot.yaml
Labels: bug
