Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-03, with the labels that each got.

#1008 Rename scantype-configMap.yml to scantype-configMap.yaml
  scanners/zap-advanced/integration-test/scantype-configMap.yaml
Labels: bug, ci

#1009 Updated ScheduledScan's operator tests to increase code coverage
  operator/controllers/execution/scheduledscan_controller_test.go
Labels: testing

#1010 Fixed folder name typo for the ZAP-Advanced scanner
  scanners/zap-advanced/integration-tests/scantype-configMap.yaml
Labels: bug

#1005 Migrate Zap Advanced to ZAPs new Reporting Addon
  scanners/zap-advanced/scanner/Dockerfile
  scanners/zap-advanced/scanner/requirements.txt
  scanners/zap-advanced/scanner/zapclient/zap_automation.py
  scanners/zap-advanced/templates/zap-advanced-scan-type.yaml
Labels: scanner, maintenance

#932 AutoDiscovery for Container Images
  auto-discovery/kubernetes/.helm-docs.gotmpl
  auto-discovery/kubernetes/.vscode/launch.json
  auto-discovery/kubernetes/.vscode/tasks.json
  auto-discovery/kubernetes/README.md
  auto-discovery/kubernetes/api/v1/autodiscoveryconfig_types.go
  auto-discovery/kubernetes/api/v1/zz_generated.deepcopy.go
  auto-discovery/kubernetes/auto-discovery-config.yaml
  auto-discovery/kubernetes/config/rbac/role.yaml
  auto-discovery/kubernetes/controllers/container_scan_controller.go
  auto-discovery/kubernetes/controllers/container_scan_controller_test.go
  auto-discovery/kubernetes/controllers/service_scan_controller.go
  auto-discovery/kubernetes/controllers/suite_test.go
  auto-discovery/kubernetes/docs/README.ArtifactHub.md
  auto-discovery/kubernetes/docs/README.DockerHub-Core.md
  auto-discovery/kubernetes/main.go
  auto-discovery/kubernetes/pkg/util/annotations.go
  auto-discovery/kubernetes/pkg/util/filter.go
  auto-discovery/kubernetes/pkg/util/gotemplate.go
  auto-discovery/kubernetes/pkg/util/gotemplate_test.go
  auto-discovery/kubernetes/values.yaml
  operator/controllers/execution/scans/scan_reconciler.go
Labels: enhancement, auto-discovery, planned

#1034 Fixes semgrep's integration test error
  scanners/semgrep/integration-tests/semgrep.test.js
Labels: bug

#936 ADR-0011: Version Numbers
  docs/adr/adr_0011.md
Labels: documentation, architecture, planned

#1022 Removed dependency on Dockerhub for Test-Scan scantypes in integration tests
  .github/workflows/ci.yaml
  scanners/test-scan/Makefile
Labels: testing, planned

#1033 Improves the integration-tests makefile process for scanners
  .github/workflows/ci.yaml
  scanners.mk
  scanners/amass/Makefile
  scanners/amass/integration-tests/amass.test.js
  scanners/cmseek/Makefile
  scanners/cmseek/integration-tests/cmseek.test.js
  scanners/git-repo-scanner/integration-tests/git-repo-scanner.test.js
  scanners/gitleaks/integration-tests/gitleaks.test.js
  scanners/helpers.js
  scanners/kube-hunter/Makefile
  scanners/kube-hunter/integration-tests/kube-hunter.test.js
  scanners/kubeaudit/Makefile
  scanners/kubeaudit/integration-tests/kubeaudit.test.js
  scanners/ncrack/Makefile
  scanners/ncrack/integration-tests/ncrack.test.js
  scanners/nikto/Makefile
  scanners/nikto/integration-tests/nikto.test.js
  scanners/nmap/Makefile
  scanners/nmap/integration-tests/nmap.test.js
  scanners/package-lock.json
  scanners/package.json
  scanners/screenshooter/Makefile
  scanners/semgrep/integration-tests/semgrep.test.js
  scanners/ssh-scan/Makefile
  scanners/ssh-scan/integration-tests/ssh-scan.test.js
  scanners/sslyze/Makefile
  scanners/sslyze/integration-tests/sslyze.test.js
  scanners/trivy/Makefile
  scanners/trivy/integration-tests/trivy.test.js
  scanners/typo3scan/Makefile
  scanners/typo3scan/integration-tests/typo3scan.test.js
  scanners/whatweb/Makefile
  scanners/whatweb/integration-tests/whatweb.test.js
  scanners/wpscan/Makefile
  scanners/wpscan/integration-tests/wpscan.test.js
  scanners/zap-advanced/integration-tests/zap-advanced.test.js
  scanners/zap/Makefile
  scanners/zap/integration-tests/zap.test.js
  tests/integration/generic/findings-validation.test.js
  tests/integration/generic/no-scan-definition-error.test.js
  tests/integration/generic/read-only-hook.test.js
  tests/integration/generic/read-write-hook.test.js
  tests/integration/scanner/__testFiles__/gitleaks-finding.txt
  tests/integration/scanner/__testFiles__/gitleaks-finding.txt.license
  tests/integration/scanner/cascade-nmap-ncrack.test.js
  tests/integration/scanner/cascade-nmap-sslyze.test.js
Labels: maintenance, testing, planned

#1046 Add frontmatter w/ sidebar config to ADRs
  docs/adr/adr_0001.md
  docs/adr/adr_0002.md
  docs/adr/adr_0003.md
  docs/adr/adr_0004.md
  docs/adr/adr_0005.md
  docs/adr/adr_0006.md
  docs/adr/adr_0007.md
  docs/adr/adr_0008.md
  docs/adr/adr_0009.md
  docs/adr/adr_0010.md
  docs/adr/adr_0011.md
Labels: enhancement, documentation

#1038 Allow Volumes & VolumeMounts Config for AutoDiscovery Scans
  auto-discovery/kubernetes/README.md
  auto-discovery/kubernetes/api/v1/autodiscoveryconfig_types.go
  auto-discovery/kubernetes/api/v1/zz_generated.deepcopy.go
  auto-discovery/kubernetes/controllers/container_scan_controller.go
  auto-discovery/kubernetes/controllers/service_scan_controller.go
  auto-discovery/kubernetes/docs/README.ArtifactHub.md
  auto-discovery/kubernetes/go.mod
  auto-discovery/kubernetes/pkg/util/gotemplate.go
  auto-discovery/kubernetes/pkg/util/gotemplate_test.go
  auto-discovery/kubernetes/pkg/util/util_suite_test.go
  auto-discovery/kubernetes/values.yaml
Labels: enhancement, auto-discovery

#1028 Inherit Makefile Integration Tests command for hooks
  hooks.mk
  hooks/cascading-scans/Makefile
  hooks/cascading-scans/hook/package.json
  hooks/cascading-scans/integration-tests/cascade-nmap-ncrack.test.js
  hooks/cascading-scans/integration-tests/cascade-nmap-sslyze.test.js
  hooks/finding-post-processing/hook/package.json
  hooks/generic-webhook/Makefile
  hooks/generic-webhook/hook/package.json
  hooks/notification/Makefile
  hooks/notification/hook/package.json
  hooks/package-lock.json
  hooks/package.json
  hooks/persistence-azure-monitor/Makefile
  hooks/persistence-azure-monitor/hook/package.json
  hooks/persistence-defectdojo/Makefile
  hooks/persistence-elastic/hook/package.json
  hooks/update-field/Makefile
  hooks/update-field/hook/package.json
Labels: testing, planned

#1050 Adding kind cluster name variable to common.mk makefile config (closes #1037)
  common.mk
Labels: maintenance

#1035 Use matrix in ci for hook integration-test
  .github/workflows/ci.yaml
  hooks/package-lock.json
  hooks/package.json
  scanners/zap-advanced/Makefile
Labels: maintenance, testing, ci, hook, planned

#1053 Minor makefile improvements for the test-all target
  .python-version
  Makefile
  common.mk
  hooks.mk
  operator/Makefile
  scanners/git-repo-scanner/Makefile
  scanners/screenshooter/parser/package-lock.json
  scanners/screenshooter/parser/package-lock.json.license
  scanners/screenshooter/parser/package.json
  scanners/screenshooter/parser/package.json.license
Labels: maintenance

#1063 Autodiscovery is now built within the CI pipeline and no longer pushes to Dockerhub
  .github/workflows/ci.yaml
Labels: maintenance, testing, planned

#1062 Demo-target build process moved to release pipeline
  .github/workflows/ci.yaml
  .github/workflows/release-build.yaml
Labels: maintenance, planned

#1064 Fixed Dependabot alerts
  hooks/cascading-scans/hook/package-lock.json
  hooks/finding-post-processing/hook/package-lock.json
  hooks/generic-webhook/hook/package-lock.json
  hooks/notification/hook/package-lock.json
  hooks/persistence-azure-monitor/hook/package-lock.json
  hooks/persistence-elastic/hook/package-lock.json
  hooks/update-field/hook/package-lock.json
  package-lock.json
  scanners/gitleaks/parser/package-lock.json
  scanners/package-lock.json
  tests/integration/package-lock.json
Labels: bug

#1066 Removed gitleaks from custom scanner build in release pipeline
  .github/workflows/release-build.yaml
Labels: bug, ci

#1079 Added missing Hook to Release Pipeline
  .github/workflows/ci.yaml
  .github/workflows/release-build.yaml
Labels: bug, ci
