Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-06, with the labels that each got.

#1204 ZAP Advanced: Fix Issue with Helm Install
  scanners/zap-advanced/templates/zap-advanced-scan-type.yaml
Labels: bug

#1209 Update Kubernetes Versions used in CI
  .github/workflows/ci.yaml
Labels: dependencies, ci

#1202 Added running unit-tests step to hooks ci steps
  .github/workflows/ci.yaml
  common.mk
Labels: bug

#1217 Fix yq compatibility
  common.mk
Labels: bug, ci

#1213 Changed the CI requirements to run on pushes to main branch and on PRs
  .github/workflows/ci.yaml
Labels: maintenance

#1219 Fixes test dependencies installation for hooks locally
  .github/workflows/ci.yaml
  env-paths.mk
  hooks.mk
Labels: bug

#1222 Increase nuclei integration test timeout
  scanners/nuclei/integration-tests/nuclei.test.js
Labels: maintenance, ci, skip-changelog, planned

#1220 Add rocket.chat Notification Hook
  hooks/notification/.helm-docs.gotmpl
  hooks/notification/README.md
  hooks/notification/docs/README.ArtifactHub.md
  hooks/notification/hook/NotifierFactory.ts
  hooks/notification/hook/NotifierType.ts
  hooks/notification/hook/Notifiers/AbstractWebHookNotifier.ts
  hooks/notification/hook/Notifiers/RocketChat.ts
  hooks/notification/hook/Notifiers/RocketChatNotifier.test.ts
  hooks/notification/hook/Notifiers/TrelloNotifier.ts
  hooks/notification/hook/hook.ts
  hooks/notification/hook/model/Finding.ts
  hooks/notification/hook/notification-templates/rocket-chat.njk
Labels: enhancement

#1210 Make Labels and Annotation consistent
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_reconciler.go
Labels: maintenance, planned

#1243 Add comments describing scan name generation in ContainerAutodiscovery
  auto-discovery/kubernetes/controllers/container_scan_controller.go
Labels: documentation, skip-changelog, auto-discovery

#1248 Fix incorrect mapping for SSLyze in DefectDojo Hook
  hooks/persistence-defectdojo/hook/build.gradle
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/util/ScanNameMapping.java
Labels: bug

#1254 Removed "dependencies" tag from scb bot PRs
  .github/workflows/scb-bot.yaml
Labels: skip-changelog
