Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-09, with the labels that each got.

#1333 Update Juice Shop URL in documentation example scans
  scanners/zap-advanced/examples/demo-juiceshop-scan-authenticated/scan.yaml
  scanners/zap-advanced/examples/demo-juiceshop-scan-unauthenticated/scan.yaml
Labels: documentation

#1334 Add Megalinter output to Gitignore file
  .gitignore
Labels: maintenance

#1291 Run Helm docs generation only on main branch
  .github/workflows/helm-docs.yaml
Labels: maintenance

#1337 Updating amass config due to recent config changes
  scanners/amass/templates/amass-scan-type.yaml
  scanners/zap-advanced/scanner/zapclient/zap_abstract_client.py
Labels: scanner, maintenance

#1339 Added podSecurityContext to all scanTypes (closes #1330)
  scanners/amass/templates/amass-scan-type.yaml
  scanners/amass/values.yaml
  scanners/angularjs-csti-scanner/templates/angularjs-csti-scanner-scan-type.yaml
  scanners/angularjs-csti-scanner/values.yaml
  scanners/cmseek/templates/cmseek-scan-type.yaml
  scanners/cmseek/values.yaml
  scanners/git-repo-scanner/templates/git-repo-scanner-scan-type.yaml
  scanners/git-repo-scanner/values.yaml
  scanners/gitleaks/templates/gitleaks-scan-type.yaml
  scanners/gitleaks/values.yaml
  scanners/kube-hunter/templates/kubehunter-scan-type.yaml
  scanners/kube-hunter/values.yaml
  scanners/kubeaudit/templates/kubeaudit-scan-type.yaml
  scanners/kubeaudit/values.yaml
  scanners/ncrack/templates/ncrack-scan-type.yaml
  scanners/ncrack/values.yaml
  scanners/nikto/templates/nikto-scan-type.yaml
  scanners/nikto/values.yaml
  scanners/nmap/templates/nmap-scan-type.yaml
  scanners/nmap/values.yaml
  scanners/nuclei/templates/nuclei-scan-type.yaml
  scanners/nuclei/values.yaml
  scanners/screenshooter/templates/screenshooter-scan-type.yaml
  scanners/screenshooter/values.yaml
  scanners/semgrep/templates/semgrep-scan-type.yaml
  scanners/semgrep/values.yaml
  scanners/ssh-scan/templates/ssh-scan-scan-type.yaml
  scanners/ssh-scan/values.yaml
  scanners/sslyze/templates/sslyze-scan-type.yaml
  scanners/sslyze/values.yaml
  scanners/test-scan/templates/test-scan-scan-type.yaml
  scanners/test-scan/values.yaml
  scanners/trivy/templates/trivy-scan-type.yaml
  scanners/trivy/values.yaml
  scanners/typo3scan/templates/typo3scan-scan-type.yaml
  scanners/typo3scan/values.yaml
  scanners/whatweb/templates/whatweb-scan-type.yaml
  scanners/whatweb/values.yaml
  scanners/wpscan/templates/wpscan-scan-type.yaml
  scanners/wpscan/values.yaml
  scanners/zap-advanced/templates/zap-advanced-scan-type.yaml
  scanners/zap-advanced/values.yaml
  scanners/zap/templates/zap-scan-type.yaml
  scanners/zap/values.yaml
Labels: scanner

#1338 Added a configuration to disable the automatic dashboard import (closes #1332)
  hooks/persistence-elastic/templates/import-dashboard.yaml
  hooks/persistence-elastic/values.yaml
Labels: persistence, maintenance, hook

#1354 Fix create-new-scanner Make target
  Makefile
Labels: bug, maintenance

#1270 ADR-0012: Initial Proposal for Cluster Wide Custom Resources (e.g. ClusterScanType)
  docs/adr/adr_0012.md
Labels: documentation, architecture, CRD

#1373 Fixing broken link in ADR 0012 to ADR 0009.
  docs/adr/adr_0012.md
Labels: bug, documentation

#1345 Remove redundant job type annotations
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_reconciler.go
Labels: maintenance, breaking, planned

#1375 Bulk bug fixes for all "Jose" Node.js dependencies
  hook-sdk/nodejs/package-lock.json
  hooks/cascading-scans/hook/package-lock.json
  hooks/notification/hook/package-lock.json
  hooks/package-lock.json
  parser-sdk/nodejs/package-lock.json
  scanners/package-lock.json
  tests/integration/package-lock.json
Labels: dependencies

#1356 ADR 15 & 16: Constraints vs Solution Strategy
  docs/adr/adr_0000.md
  docs/adr/adr_0015.md
  docs/adr/adr_0016.md
Labels: documentation, architecture

#1336 ADR-0014: Metrics Collection
  docs/adr/adr_0014.md
Labels: documentation, architecture

#1360 Renamed the docker images of demo-targets to include a "demo-target-" prefix
  .github/workflows/release-build.yaml
  UPGRADING.md
  demo-targets/old-joomla/values.yaml
  demo-targets/old-typo3/values.yaml
  demo-targets/old-wordpress/values.yaml
Labels: ci, breaking

#1335 ADR-0013: Autodiscovery v2
  docs/adr/adr_0013.md
Labels: documentation, architecture, auto-discovery

#1328 Change name of container autodiscovery scans
  UPGRADING.md
  auto-discovery/kubernetes/controllers/container_scan_controller.go
  auto-discovery/kubernetes/controllers/container_scan_controller_test.go
Labels: auto-discovery, breaking

#1351 Upgrade Operator & AutoDiscovery to latest kubebuilder 3.6.0 dependencies
  .github/workflows/ci.yaml
  auto-discovery/kubernetes/Dockerfile
  auto-discovery/kubernetes/Makefile
  auto-discovery/kubernetes/api/v1/autodiscoveryconfig_types.go
  auto-discovery/kubernetes/api/v1/groupversion_info.go
  auto-discovery/kubernetes/controllers/service_scan_controller.go
  auto-discovery/kubernetes/go.mod
  auto-discovery/kubernetes/go.sum
  lurker/Dockerfile
  lurker/go.mod
  lurker/go.sum
  operator/Dockerfile
  operator/Makefile
  operator/apis/cascading/v1/groupversion_info.go
  operator/apis/execution/v1/groupversion_info.go
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_parsedefinitions.yaml
  operator/config/crd/bases/execution.securecodebox.io_scancompletionhooks.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scantypes.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_parsedefinitions.yaml
  operator/crds/execution.securecodebox.io_scancompletionhooks.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scantypes.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
  operator/go.mod
  operator/go.sum
Labels: dependencies, maintenance, breaking

#1347 Disable cascading rules by default
  .templates/new-scanner/values.yaml
  UPGRADING.md
  hooks/cascading-scans/Makefile
  scanners/cmseek/values.yaml
  scanners/gitleaks/values.yaml
  scanners/kube-hunter/values.yaml
  scanners/ncrack/values.yaml
  scanners/nikto/values.yaml
  scanners/nmap/values.yaml
  scanners/nuclei/values.yaml
  scanners/screenshooter/values.yaml
  scanners/semgrep/values.yaml
  scanners/ssh-scan/values.yaml
  scanners/sslyze/values.yaml
  scanners/typo3scan/values.yaml
  scanners/whatweb/values.yaml
  scanners/zap-advanced/values.yaml
  scanners/zap/values.yaml
Labels: maintenance, breaking, cascading-scans, planned
