Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-10, with the labels that each got.

#1393 fix zap integration-test (no issue to link)
  scanners/zap/integration-tests/zap.test.js
Labels: bug

#1401 fix(minio): Fixed port forward script to fit change to bitnami minio charts
  bin/minio-port-forward.sh
Labels: bug

#1349 Add managed by label to required labels in service autodiscovery
  UPGRADING.md
  auto-discovery/kubernetes/controllers/service_scan_controller.go
Labels: breaking

#1389 Generate S3 URLs from go template
  operator/controllers/execution/scans/hook_reconciler.go
  operator/controllers/execution/scans/parse_reconciler.go
  operator/controllers/execution/scans/scan_controller.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/templates/manager/manager.yaml
  operator/values.yaml
Labels: enhancement

#1406 fix: Formatting for operator rbac manager service account (closes #1405)
  operator/templates/rbac/serviceaccount.yaml
Labels: bug

#1415 fix(jest): Combines both the config files for jest and sets it to 27.0.6
  common.mk
  hooks/jest.config.js
  hooks/package-lock.json
  hooks/package.json
  tests/integration/package-lock.json
  tests/integration/package.json
Labels: bug

#1357 Issue 1353 make fails spaces in path
  Makefile
  auto-discovery/kubernetes/Makefile
  bin/npm-ci-all.sh
  docs/adr/adr_0018.md
  env-paths.mk
  hooks.mk
  hooks/Makefile
  hooks/finding-post-processing/Makefile
  hooks/persistence-elastic/Makefile
  operator/Makefile
  prerequisites.mk
  scanners.mk
  scanners/Makefile
  scanners/cmseek/Makefile
  scanners/git-repo-scanner/Makefile
  scanners/kubeaudit/Makefile
  scanners/ncrack/Makefile
  scanners/nikto/Makefile
  scanners/nuclei/Makefile
  scanners/screenshooter/Makefile
  scanners/semgrep/Makefile
  scanners/ssh-scan/Makefile
  scanners/zap-advanced/scanner/Makefile
  sdk.mk
  test-base.mk
Labels: bug
