Repository secureCodeBox/secureCodeBox, pull requests merged in 2022-01, with the labels that each got.

#909 Enabled version control for Typo3Scan
  .github/workflows/scb-bot.yaml
  scanners/nuclei/docs/README.DockerHub-Parser.md
  scanners/typo3scan/Chart.yaml
  scanners/typo3scan/README.md
  scanners/typo3scan/docs/README.DockerHub-Parser.md
  scanners/typo3scan/docs/README.DockerHub-Scanner.md
  scanners/typo3scan/scanner/Dockerfile
Labels: scanner

#917 Fix Typo in Notification Hook Docs
  hooks/notification/.helm-docs.gotmpl
  hooks/notification/README.md
  hooks/notification/docs/README.ArtifactHub.md
Labels: documentation

#916 Update to JuiceShop 13.0.3
  demo-targets/juice-shop/Chart.yaml
  demo-targets/juice-shop/README.md
Labels: dependencies, maintenance

#920 Update Nuclei cascading rule to include protocol information and allow alternative HTTP ports
  scanners/nuclei/cascading-rules/subdomain_http.yaml
  scanners/nuclei/cascading-rules/subdomain_https.yaml
Labels: bug, scanner

#923 Fix logging of cascading scan name
  hooks/cascading-scans/hook/scan-helpers.ts
Labels: bug

#933 Rename example files for zap-advanced to avoid docusaurus error
  scanners/zap-advanced/examples/integration-tests/scantype-configMap.yaml
  scanners/zap-advanced/examples/nginx/0-foo.yaml
Labels: bug

#934 Remove JCenter Repo from DefectDojo Hook
  hooks/persistence-defectdojo/hook/build.gradle
Labels: maintenance, ci

#919 Update Operators & Lurkers Go Version and Go Dependencies
  .github/workflows/ci.yaml
  lurker/Dockerfile
  lurker/go.mod
  lurker/go.sum
  lurker/main.go
  operator/Dockerfile
  operator/config/crd/bases/cascading.securecodebox.io_cascadingrules.yaml
  operator/config/crd/bases/execution.securecodebox.io_parsedefinitions.yaml
  operator/config/crd/bases/execution.securecodebox.io_scancompletionhooks.yaml
  operator/config/crd/bases/execution.securecodebox.io_scans.yaml
  operator/config/crd/bases/execution.securecodebox.io_scantypes.yaml
  operator/config/crd/bases/execution.securecodebox.io_scheduledscans.yaml
  operator/crds/cascading.securecodebox.io_cascadingrules.yaml
  operator/crds/execution.securecodebox.io_parsedefinitions.yaml
  operator/crds/execution.securecodebox.io_scancompletionhooks.yaml
  operator/crds/execution.securecodebox.io_scans.yaml
  operator/crds/execution.securecodebox.io_scantypes.yaml
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
  operator/go.mod
  operator/go.sum
  operator/utils/hash_test.go
Labels: dependencies, maintenance

#946 Fix Email Reciever Field in Notification Hook
  hooks/notification/.helm-docs.gotmpl
  hooks/notification/README.md
  hooks/notification/docs/README.ArtifactHub.md
  hooks/notification/hook/Notifiers/AbstractNotifier.ts
  hooks/notification/hook/Notifiers/AbstractWebHookNotifier.ts
  hooks/notification/hook/Notifiers/EMailNotifier.test.ts
  hooks/notification/hook/Notifiers/EMailNotifier.ts
  hooks/notification/hook/hook.ts
  hooks/notification/hook/notification-templates/email.njk
Labels: bug
