Repository secureCodeBox/secureCodeBox, pull requests merged in 2023-09, with the labels that each got.

#1889 Add note about resource limits for persistence-defectdojo hook
  hooks/persistence-defectdojo/.helm-docs.gotmpl
Labels: maintenance

#1897 Rename leftover lurcher to lurker
  .github/workflows/release-build.yaml
Labels: bug, maintenance

#1900 Clarify documentation that scans and hooks/scanners must be deleted before the operator
  documentation/docs/getting-started/uninstallation.md
Labels: documentation

#1937 Move dependabot configuration file to correct location
  .github/dependabot.yml
Labels: bug

#1946 Remove unused language versions (fixes #1945)
  .github/workflows/release-build.yaml
Labels: maintenance, ci

#1896 Upgrade node to latest LTS in templates
  .templates/new-scanner/parser/Dockerfile
Labels: dependencies, maintenance, ci

#1950 #942 Replace sponsor image paths to documentation path
  README.md
  resources/sponsors/Logo_iteratec.svg
  resources/sponsors/Logo_sda-se.png
  resources/sponsors/Logo_secura.svg
  resources/sponsors/Logo_signal-iduna.svg
  resources/sponsors/Logo_timo-pagel-it-consulting.png
Labels: documentation

#1951 Remove GitHub Actions warnings
  .github/workflows/ci.yaml
Labels: ci

#1974 Fix version in Dockerfile and prevent issues by generalizing the app name
  hooks/persistence-defectdojo/hook/Dockerfile
Labels: bug

#1988 Ignore .license files for hook helm charts
  hooks/cascading-scans/.helmignore
  hooks/finding-post-processing/.helmignore
  hooks/generic-webhook/.helmignore
  hooks/notification/.helmignore
  hooks/persistence-azure-monitor/.helmignore
  hooks/persistence-defectdojo/.helmignore
  hooks/update-field-hook/.helmignore
Labels: ci, skip-changelog

#1986 Bump docusaurus packages to 2.4.3 in documentation
  documentation/package-lock.json
  documentation/package.json
Labels: dependencies

#1989 Ignore .license file in elasticsearch hook chart too
  hooks/persistence-elastic/.helmignore
Labels: ci, skip-changelog

#1995 Skip trivy k8 test until we fixed #1982
  scanners/trivy/integration-tests/trivy.test.js
Labels: maintenance

#1994 Remove 'interval' from required properties as ScheduledScan can be defined by 'schedule' too
  operator/crds/execution.securecodebox.io_scheduledscans.yaml
Labels: bug

#1961 Add SPDX Header License Check To PRs
  .github/workflows/license-check.yaml
Labels: enhancement, ci

#1996 Add missing affinity and tolerations properties to hooks
  hooks/persistence-azure-monitor/templates/persistence-provider.yaml
  hooks/persistence-defectdojo/templates/persistence-provider.yaml
  hooks/persistence-elastic/templates/persistence-provider.yaml
Labels: bug

#1957 Add architecture decision for OpenVAS integration
  documentation/docs/architecture/09_architecture_decisions/adr_0019.md
Labels: documentation
