Repository secureCodeBox/secureCodeBox, pull requests merged in 2023-07, with the labels that each got.

#1782 [Snyk] Upgrade ts-jest from 29.0.5 to 29.1.0
  scanners/package-lock.json
  scanners/package.json
Labels: dependencies

#1787 Fixes the tests of Trivy and adds a check for empty scanResults
  scanners/trivy/parser/__testFiles__/juice-shop-v12.10.2-no-results.json
  scanners/trivy/parser/parser.js
  scanners/trivy/parser/parser.test.js
Labels: bug

#1795 Add Heiko Kiesel to contributors
  CONTRIBUTORS.md
Labels: documentation

#1791 Implemented the failIfFoundUrlsLessThan and warnIfFoundUrlsLessthan settings in ZAP Advanced
  scanners/zap-advanced/scanner/zapclient/spider/zap_spider_ajax.py
  scanners/zap-advanced/scanner/zapclient/spider/zap_spider_http.py
Labels: bug

#1808 Bump semver from 6.3.0 to 6.3.1
  hooks/cascading-scans/hook/package-lock.json
  hooks/finding-post-processing/hook/package-lock.json
  hooks/generic-webhook/hook/package-lock.json
  hooks/persistence-elastic/hook/package-lock.json
  hooks/update-field-hook/hook/package-lock.json
  tests/integration/package-lock.json
Labels: dependencies

#1801 Fixed Bug ErrImagePull in SSH-audit parser
  .github/workflows/release-build.yaml
  .github/workflows/scb-bot.yaml
  operator/internal/telemetry/telemetry.go
Labels: bug, scanner

#1813 Updated the PyYAML package in pull-secret-example to include patch fix
  auto-discovery/kubernetes/pull-secret-extractor/requirements.txt
Labels: skip-changelog

#1818 Adjustments to defectdojo-client
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/strategies/VersionedEngagementsStrategy.java
Labels: bug

#1815 Lower case argument names for gpg action for SCB-BOT
  .github/workflows/scb-bot.yaml
Labels: skip-changelog

#1828 Downgrade amass version to v3.23.3
  scanners/amass/Chart.yaml
  scanners/amass/README.md
Labels: bug, scanner

#1832 Changed SCB-Bot to check all PRs for exisiting upgrade PRs
  .github/workflows/scb-bot.yaml
Labels: maintenance

#1839 Fixed typo in the secret creation example in the operator.s3 yaml
  operator/values.yaml
Labels: maintenance, skip-changelog

#1841 Upgraded CI base images to latest LTS version i.e 22.04
  .github/workflows/ci.yaml
  .github/workflows/label-commenter.yml
Labels: maintenance

#1842 Explicitly install the tools kubectl/helm/kind in the CI
  .github/workflows/ci.yaml
Labels: maintenance
