Repository secureCodeBox/secureCodeBox, pull requests merged in 2023-10, with the labels that each got.

#2011 Add missing licenses for SBOM workflow
  hooks/persistence-dependencytrack/templates/_helpers.tpl
  scanners/trivy-sbom/parser/__testFiles__/hello-world-cyclonedx.json.license
  scanners/trivy-sbom/parser/package-lock.json.license
  scanners/trivy-sbom/parser/package.json.license
Labels: bug

#2025 Use ZAP Docker images from SSP repo
  scanners/zap-advanced/tests/__snapshot__/scanner_test.yaml.snap
  scanners/zap-advanced/values.yaml
  scanners/zap/tests/__snapshot__/scanner_test.yaml.snap
  scanners/zap/values.yaml
Labels: scanner, maintenance

#2027 Fix path to iteratec logo in main README.md
  README.md
Labels: bug

#2060 Add missing docs to Dependency-Track hook
  hooks/persistence-dependencytrack/docs/README.ArtifactHub.md
  hooks/persistence-dependencytrack/docs/README.DockerHub-Hook.md
Labels: bug

#2068 Update NPM Dependencies
  documentation/package-lock.json
  documentation/package.json
Labels: dependencies

#2017 #1642 Decission About Integration OpenVAS
  documentation/docs/architecture/09_architecture_decisions/adr_0019.md
Labels: documentation, architecture

#2052 Fixed Trivy K8s Scan
  scanners/trivy/integration-tests/trivy.test.js
Labels: bug

#2072 Change Primary Community "Channel" from Slack to Github Discussions & Issues
  README.md
Labels: documentation
