Repository secureCodeBox/secureCodeBox, pull requests merged in 2023-08, with the labels that each got.

#1857 Use latest version of DefectDojo Client lib
  hooks/persistence-defectdojo/hook/build.gradle
Labels: dependencies

#1862 Refresh Helm Docs Update CI
  .github/workflows/helm-docs.yaml
Labels: bug

#1866 Add logo to helm docs and README
  scanners/kube-hunter/.helm-docs.gotmpl
  scanners/kube-hunter/README.md
Labels: documentation

#1875 Remove skipped test against securecodebox.io
  scanners/nuclei/integration-tests/nuclei.test.js
Labels: maintenance, testing

#1876 Link ffuf GitHub repo in README
  scanners/ffuf/.helm-docs.gotmpl
Labels: documentation

#1870 Improve SSLyze examples
  scanners/sslyze/examples/example.com/findings.json
  scanners/sslyze/examples/example.com/sslyze-results.json
  scanners/sslyze/examples/secureCodeBox.io/findings.json
  scanners/sslyze/examples/secureCodeBox.io/sslyze-results.json
Labels: documentation

#1856 Added sslyze parser check for successful ASN1 certificate parsing
  scanners/sslyze/parser/__testFiles__/no-certificate_deployments.json
  scanners/sslyze/parser/parser.js
  scanners/sslyze/parser/parser.test.js
Labels: bug

#1878 Fix documentation findings
  scanners/gitleaks/examples/secureCodeBox/findings.yaml
  scanners/ncrack/examples/dummy-ssh/findings.yaml
  scanners/nikto/examples/demo-bodgeit/findings.yaml
  scanners/nikto/examples/demo-docs.securecodebox.io/findings.yaml
  scanners/nikto/examples/demo-docs.securecodebox.io/nikto-results.json.license
  scanners/nikto/examples/demo-juice-shop/findings.yaml
  scanners/nmap/parser/__testFiles__/findings.yaml
  scanners/screenshooter/examples/securecodebox.io/findings.yaml
  scanners/sslyze/examples/example.com/findings.yaml
  scanners/sslyze/examples/example.com/sslyze-results.json.license
  scanners/sslyze/examples/secureCodeBox.io/findings.json
  scanners/sslyze/examples/secureCodeBox.io/findings.yaml
  scanners/sslyze/examples/secureCodeBox.io/sslyze-results.json.license
Labels: documentation
