Repository secureCodeBox/secureCodeBox, pull requests merged in 2023-03, with the labels that each got.

#1610 [Snyk] Upgrade axios from 1.2.5 to 1.3.1
  hooks/package-lock.json
  hooks/package.json
Labels: dependencies

#1625 Removed unnecessary intializing of scannerVersions in scanner Dockerfiles
  scanners/kube-hunter/scanner/Dockerfile
  scanners/kubeaudit/scanner/Dockerfile
  scanners/ncrack/scanner/Dockerfile
  scanners/nmap/scanner/Dockerfile
  scanners/whatweb/scanner/Dockerfile
Labels: maintenance

#1631 Fix the link in ADR-0017 in order to fix the Netlify build
  docs/adr/adr_0017.md
Labels: bug

#1632 Added `zap-advanced`configuration option to change reportType
  scanners/zap-advanced/templates/zap-advanced-scan-type.yaml
  scanners/zap-advanced/values.yaml
Labels: scanner

#1628 Maintenance - added/fixed missing scantypes
  operator/internal/telemetry/telemetry.go
Labels: maintenance

#1635 [Snyk] Upgrade axios from 1.2.5 to 1.3.3
  parser-sdk/nodejs/package-lock.json
  parser-sdk/nodejs/package.json
Labels: dependencies

#1638 The DRAFT status does not have a link, only the SUPERSEDES does
  docs/adr/adr_0017.md
Labels: bug, documentation

#1640 Added a check for empty Trivy `.Results`
  scanners/trivy/parser/__testFiles__/juice-shop-v12.10.2-empty-results.json
  scanners/trivy/parser/parser.js
  scanners/trivy/parser/parser.test.js
Labels: bug

#1650 [Snyk] Upgrade axios from 1.3.3 to 1.3.4
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
Labels: dependencies

#1645 Enforced the use of the node version in .nvmrc
  .github/workflows/ci.yaml
Labels: ci

#1655 Updated snapshot of typo3scan after upgrade
  scanners/typo3scan/integration-tests/typo3scan.test.js
Labels: bug

#1446 Added new DNS Scanner: Doggo
  operator/internal/telemetry/telemetry.go
  scanners/doggo/.gitignore
  scanners/doggo/.helm-docs.gotmpl
  scanners/doggo/.helmignore
  scanners/doggo/Chart.yaml
  scanners/doggo/Makefile
  scanners/doggo/README.md
  scanners/doggo/cascading-rules/.gitkeep
  scanners/doggo/cascading-rules/dnsscan.yaml
  scanners/doggo/docs/.gitkeep
  scanners/doggo/examples/example.com/findings.yaml
  scanners/doggo/examples/example.com/scan.yaml
  scanners/doggo/integration-tests/doggo.test.js
  scanners/doggo/integration-tests/jest.config.json
  scanners/doggo/parser/.dockerignore
  scanners/doggo/parser/Dockerfile
  scanners/doggo/parser/__snapshots__/parser.test.js.snap
  scanners/doggo/parser/__testFiles__/empty.json
  scanners/doggo/parser/__testFiles__/example.com.json
  scanners/doggo/parser/parser.js
  scanners/doggo/parser/parser.test.js
  scanners/doggo/scanner/Dockerfile
  scanners/doggo/scanner/wrapper.sh
  scanners/doggo/templates/cascading-rules.yaml
  scanners/doggo/templates/doggo-parse-definition.yaml
  scanners/doggo/templates/doggo-scan-type.yaml
  scanners/doggo/values.yaml
Labels: enhancement, scanner

#1657 #709 Try if this makes the license recognizable by the pkg.go.dev
  operator/LICENSE
Labels: bug
