Repository secureCodeBox/secureCodeBox, pull requests merged in 2023-02, with the labels that each got.

#1570 maitenance(scb-bot): One failing matrix job no longer stops other version compare jobs
  .github/workflows/scb-bot.yaml
Labels: maintenance

#1580 Fix that ADR 17 Breaks Documentation
  docs/adr/adr_0017.md
Labels: bug, documentation

#1582 [Snyk] Upgrade axios from 1.2.2 to 1.2.3
  hooks/package-lock.json
  hooks/package.json
Labels: dependencies

#1597 [Snyk] Upgrade @kubernetes/client-node from 0.18.0 to 0.18.1
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
Labels: dependencies

#1606 [Snyk] Upgrade axios from 1.2.2 to 1.3.0
  hook-sdk/nodejs/package-lock.json
  hook-sdk/nodejs/package.json
Labels: dependencies

#1434 Added optional `identified at` parameter to findings
  scanners/amass/parser/__snapshots__/parser.test.js.snap
  scanners/amass/parser/parser.js
  scanners/amass/parser/parser.test.js
  scanners/cmseek/parser/__snapshots__/parser.test.js.snap
  scanners/cmseek/parser/parser.js
  scanners/ffuf/parser/parser.js
  scanners/ffuf/parser/parser.test.js
  scanners/kubeaudit/parser/__snapshots__/parser.test.js.snap
  scanners/kubeaudit/parser/parser.js
  scanners/nuclei/parser/__snapshots__/parser.test.js.snap
  scanners/nuclei/parser/parser.js
  scanners/ssh-scan/parser/parser.js
  scanners/ssh-scan/parser/parser.test.js
  scanners/sslyze/parser/parser.js
  scanners/sslyze/parser/parser.test.js
  scanners/wpscan/parser/parser.js
  scanners/wpscan/parser/parser.test.js
Labels: findings

#1526 Add Apikey in generic webhook
  CONTRIBUTORS.md
  hooks/generic-webhook/README.md
  hooks/generic-webhook/docs/README.ArtifactHub.md
  hooks/generic-webhook/hook/hook.js
  hooks/generic-webhook/templates/webhook-hook.yaml
  hooks/generic-webhook/values.yaml
Labels: hook
