Repository secureCodeBox/secureCodeBox, pull requests merged in 2023-06, with the labels that each got.

#1742 #1741 decrease number of expected results
  scanners/nuclei/integration-tests/nuclei.test.js
Labels: bug, ci

#1734 Update s3UrlTemplate to be grouped with other s3 configs values
  operator/docs/README.ArtifactHub.md
  operator/templates/manager/manager.yaml
  operator/values.yaml
Labels: bug

#1780 Update kind node version used in CI
  .github/workflows/ci.yaml
Labels: bug, ci, skip-changelog

#1786 Updated typo3scan snapshots after upgrade
  scanners/typo3scan/integration-tests/typo3scan.test.js
Labels: skip-changelog
