Repository secureCodeBox/secureCodeBox, pull requests merged in 2024-11, with the labels that each got.

#2743 Updated Nikto Snapshot
  scanners/nikto/integration-tests/nikto.test.js
Labels: skip-changelog

#2745 DefectDojo Client Lib 3.0.0 is Broken
  hooks/persistence-defectdojo/hook/build.gradle
Labels: dependencies

#2757 No Idea Why PRevious Command Didn't Work
  documentation/blog/2024-10-25-run-x86-images-with-kubernetes-on-apple-silicon.md
Labels: documentation

#2746 Temporary Ignore Broken Defect Dojo Client Lib
  .github/dependabot.yml
Labels: dependencies

#2766 Updated configuration for npm dependency management
  .github/dependabot.yml
Labels: skip-changelog
