Repository secureCodeBox/secureCodeBox, pull requests merged in 2024-04, with the labels that each got.

#2418 Add Our Awesome Contributors
  README.md
Labels: enhancement

#2448 Dependabot bundles PRs
  .github/dependabot.yml
Labels: maintenance

#2454 Removed ESLint and related packages as dependencies
  documentation/package-lock.json
  documentation/package.json
  package-lock.json
  package.json
Labels: maintenance

#2458 Remove Ultra Mega Outdated Screenshot
  README.md
  resources/macbook_kibana.jpg
Labels: documentation
