Repository secureCodeBox/secureCodeBox, pull requests merged in 2024-07, with the labels that each got.

#2562 Switch pipeline to use the same user / variable everywhere
  .github/workflows/release-build.yaml
Labels: ci

#2578 Fix Health/Readyness Check Issues with Kubernetes AutoDiscovery
  auto-discovery/kubernetes/auto-discovery-config.yaml
  auto-discovery/kubernetes/main.go
  auto-discovery/kubernetes/pkg/config/autodiscovery_config.go
Labels: bug, auto-discovery

#2583 Pin to Node.js Version in CI to 22.4 until node issue is resolved
  .nvmrc
Labels: ci, skip-changelog

#2589 Revert "Pin to node 22.4 until node issue is resolved"
  .nvmrc
Labels: skip-changelog

#2599 Use Latest DefectDojo Client Lib
  hooks/persistence-defectdojo/hook/build.gradle
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapper.java
  hooks/persistence-defectdojo/hook/src/test/java/io/securecodebox/persistence/mapping/DefectDojoFindingToSecureCodeBoxMapperTest.java
Labels: dependencies
