Repository secureCodeBox/secureCodeBox, pull requests merged in 2024-10, with the labels that each got.

#2674 #302 Added notes to operator documentation
  documentation/docs/contributing/operator.md
Labels: documentation

#2675 Added documentation for labels of CascadingRules
  hooks/cascading-scans/docs/README.ArtifactHub.md
Labels: documentation

#2702 Deprecation Notice for deprecated Scanners
  scanners/kubeaudit/.helm-docs.gotmpl
  scanners/kubeaudit/README.md
  scanners/kubeaudit/docs/README.ArtifactHub.md
  scanners/kubeaudit/docs/README.DockerHub-Parser.md
  scanners/kubeaudit/docs/README.DockerHub-Scanner.md
  scanners/ssh-scan/.helm-docs.gotmpl
  scanners/ssh-scan/README.md
  scanners/ssh-scan/docs/README.ArtifactHub.md
  scanners/ssh-scan/docs/README.DockerHub-Parser.md
  scanners/typo3scan/.helm-docs.gotmpl
  scanners/typo3scan/README.md
  scanners/typo3scan/docs/README.ArtifactHub.md
  scanners/typo3scan/docs/README.DockerHub-Parser.md
  scanners/typo3scan/docs/README.DockerHub-Scanner.md
Labels: documentation

#2726 Fix non-existing trivy sbom parser image
  scanners/trivy-sbom/values.yaml
Labels: bug

#2728 Move copy right stuff to sidecar file
  .python-version
  .python-version.license
Labels: bug, documentation
