Repository secureCodeBox/secureCodeBox, pull requests merged in 2024-03, with the labels that each got.

#2335 fix typo in documentation
  documentation/docs/getting-started/installation.md
Labels: enhancement, documentation

#2336 Ensure Lurker Does Not Run Out of Memory When Uploading Large Scan Results
  lurker/main.go
Labels: enhancement

#2401 Pinned setup-envtest version
  auto-discovery/cloud-aws/Makefile
  auto-discovery/kubernetes/Makefile
  operator/Makefile
Labels: maintenance

#2390 Fixes mapping of Trivy Scantypes to Defectfdojo
  hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/util/ScanNameMapping.java
Labels: bug
