Repository secureCodeBox/secureCodeBox, pull requests merged in 2025-08, with the labels that each got.

#3172 Correct duplicated hostname reference in CascadingHook docs
  documentation/docs/api/crds/cascading-rule.md
Labels: documentation

#3180 Add gomod to dependabot and remove docker dep
  .github/dependabot.yml
Labels: dependencies

#3192 Remove unused docker-compose and rancher questions files
  demo-targets/bodgeit/container/docker-compose.yml
  demo-targets/bodgeit/questions.yml
  demo-targets/dummy-ssh/container/docker-compose.yml
  demo-targets/dummy-ssh/questions.yml
  demo-targets/http-webhook/container/docker-compose.yml
  demo-targets/juice-shop/container/docker-compose.yml
  demo-targets/juice-shop/questions.yml
  demo-targets/old-joomla/questions.yml
  demo-targets/old-typo3/questions.yml
  demo-targets/old-wordpress/questions.yml
  demo-targets/swagger-petstore/container/docker-compose.yml
  demo-targets/swagger-petstore/questions.yml
  demo-targets/unsafe-https/container/docker-compose.yml
  demo-targets/unsafe-https/questions.yml
  demo-targets/vulnerable-log4j/questions.yml
Labels: skip-changelog

#3196 Update renovate bot for demo-targets
  demo-targets/dummy-ssh/Chart.yaml
  demo-targets/juice-shop/Chart.yaml
  demo-targets/swagger-petstore/Chart.yaml
  demo-targets/unsafe-https/Chart.yaml
  renovate.json
Labels: dependencies

#3203 Automatically set labels for renovate PRs
  renovate.json
Labels: maintenance

#3206 Optimize Go Docker builds with native cross-compilation
  auto-discovery/cloud-aws/Dockerfile
  auto-discovery/kubernetes/Dockerfile
  lurker/Dockerfile
  operator/Dockerfile
  scanners/ffuf/scanner/Dockerfile
Labels: maintenance

#3226 Migrate scan kubernetes finalizers to avoid warnings about non-recommended finalizer url structure
  operator/controllers/execution/scans/scan_controller.go
  operator/controllers/execution/scans/scan_reconciler.go
  operator/controllers/execution/scans/scan_reconciler_test.go
Labels: bug

#3244 Remove unnecessary create-blog-post script
  bin/create-blog-post.sh
Labels: maintenance
